### ISSUE TITLE
Extend max reset password token TTL

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#1003]
The engineering team is extending the reset password token ttl max value to 21 days - it's currently 7. This change will be released this week.

We have a hardcoded max in the SDK of 168 hours (or 7 days). We need to update `DefaultPasswordPolicy.setResetTokenTtlHours` to use `504` (21 days).

I am wondering if the assertion should be there at all? Sure, it would save an API call, but it's more to maintain in the SDK. If that check were not there, we would not need to do anything with this backend update.

**Comment by mraible** [comment]
@dogeared Are you saying the following line:

```
Assert.isTrue(resetTokenTtl > 0 && resetTokenTtl < 169, "resetTokenTtl must be a positive integer, less than 169.");
```

Should be updated to use 505 instead of 169?
