### ISSUE TITLE
Bad link in docs

### ISSUE THREAD

**Issue by benmccann** [stormpath/stormpath-sdk-java#101]
http://docs.stormpath.com/rest/product-guide/ has a bad link in the text "Java: Sauthc1Signer (the sign method)"

**Comment by lhazlewood** [comment]
@omgitstom has this been fixed?

**Comment by omgitstom** [comment]
No - I wasn't tracking this associated with doc changes, this will be fixed when I get to internal issue AM-2612 though.  Which should be next week.

**Comment by dogeared** [comment]
@omgitstom - The original link goes to the old product guide. Is this issue still relevant?

**Comment by dogeared** [comment]
We no longer use the old product guide. Closing as the new "one product guide" has the correct links.
