### ISSUE TITLE
the sdk throws foreign JWT exception

### ISSUE THREAD

**Issue by francisdb** [stormpath/stormpath-sdk-java#1018]
The sdk contains `com.stormpath.sdk.error.jwt.InvalidJwtException` but in multiple places `io.jsonwebtoken.JwtException` is thrown.

I guess it would be cleaner for the sdk to only throw Stormpath (or general java) exceptions? The fact that you internally are using the io.jsonwebtoken.jwt library should not be visible to the users?

Also you could provide a bit more info to the user on what actually went wrong? I tried to reproduce a case where we see this JwtException from time to time and failed to do so because it could be a lot of things.

https://github.com/stormpath/stormpath-sdk-java/blob/9590dcaa21d7ba2ae46ca05108f87f9cab4e6b79/impl/src/main/java/com/stormpath/sdk/impl/oauth/DefaultOAuthBearerRequestAuthenticator.java#L94
https://github.com/stormpath/stormpath-sdk-java/blob/9590dcaa21d7ba2ae46ca05108f87f9cab4e6b79/impl/src/main/java/com/stormpath/sdk/impl/oauth/DefaultOAuthBearerRequestAuthenticator.java#L108
https://github.com/stormpath/stormpath-sdk-java/blob/3b5d68792cd60f413427505c7bd7772b95406d77/impl/src/main/java/com/stormpath/sdk/impl/oauth/DefaultAccessToken.java#L55

**Comment by mrioan** [comment]
This functionality is not critical and will have impact on existent developer's code (i.e. existent code will fail to catch the new exceptions while they are catching them all just fine now). We have therefore decided to postpone this PR until we release `2.0.0`. It has already been implementd. Some minor changes will be required: https://github.com/stormpath/stormpath-sdk-java/pull/1021
