### ISSUE TITLE
NullPointerException when trying to delete token in CookieAccountResolver

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#1025]
There is a bug in this line: https://github.com/stormpath/stormpath-sdk-java/blob/master/extensions/servlet/src/main/java/com/stormpath/sdk/servlet/filter/account/CookieAccountResolver.java#L146

When the `access_token` or `refresh_token` are not present the `delete` operation causes a `NullPointerException`.

`Delete` operation must check cookie is not null.

See https://stormpath.zendesk.com/agent/tickets/9582

**Comment by nlalitha** [comment]
Which releasing is having this fix?

**Comment by mrioan** [comment]
Hello @nlalitha... This is fixed in our latest release `1.1.1`
