### ISSUE TITLE
Stormpath filter gets hit for static assets (e.g. JavaScript files), causing performance issues

### ISSUE THREAD

**Issue by mraible** [stormpath/stormpath-sdk-java#1031]
I found this issue while integrating Stormpath into a JHipster application. To reproduce, you can run https://github.com/mraible/jhipster-stormpath-example. I've also created https://github.com/mraible/jhipster-stormpath-example/issues/10 to track this as part of that project.

Without Stormpath enabled (in `SecurityConfiguration.java`), most JS files take under 100ms to load. The app finishes loading in 1.55s. When Stormpath is enabled, some JS files take over 2 seconds to load. The app finishes loading in 4.3s, and the server logs are filled with:

```
2016-10-07 14:20:55.961 DEBUG 71718 --- [nio-8080-exec-6]
 enticationSpringSecurityProcessingFilter : No token in request, will continue chain.
```

Adding `<logger name="com.stormpath.spring" level="WARN"/>` to quiet the logs does not improve load times.

Level of concern: high. This a bad developer experience because you have to wait for the files to load if you have caching turned off in Chrome Developer Tools.

**Comment by lhazlewood** [comment]
Any ideas on why this is happening?  And a recommended solution?

**Comment by mraible** [comment]
I believe it's happening because we filter all requests. Spring Boot will, by default, permit access to `/css/**`, `/js/**`, `/images/**`, and `/**/favicon.ico`. We should do something similar. 

http://stackoverflow.com/questions/24916894/serving-static-web-resources-in-spring-boot-spring-security-application
