### ISSUE TITLE
Fix linkedin integration to properly use `state` param and redirect

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#1037]
As it currently stands, the linkedin login is _not_ working in the servlet or the spring integrations.

Here's what exists now:

After configuring a linked application and setting up a linkedin directory in stormpath, the request to linkedin from the servlet integration (when you click the linkedin button on the login form) looks like this:

https://www.linkedin.com/uas/oauth2/authorization?client_id=78sy7tpcmyb9ks&response_type=code&scope=r_emailaddress+r_basicprofile&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fcallbacks%2Flinkedin&state=

Notice the dangling "state=" at the end. This request fails:

Inline image 1

Here's what linkedin has to say: https://developer.linkedin.com/docs/oauth2

The state param is required. Maybe it wasn't in the past?

If I put something in the state param, then the request proceeds:

https://www.linkedin.com/uas/oauth2/authorization?client_id=78sy7tpcmyb9ks&response_type=code&scope=r_emailaddress+r_basicprofile&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fcallbacks%2Flinkedin&state=abcdef

Now, I can login to linkedin. However, it looks like whatever's in the state param ends up being part of the redirect for some reason:

http://localhost:8080/callbacks/abcdef#!

**Comment by mrioan** [comment]
@dogeared could this be related to #1030 ?

**Comment by dogeared** [comment]
#1082 & #1086 fixes this. Closing.
