### ISSUE TITLE
logout -> invalidateHttpSession = false ignored?

### ISSUE THREAD

**Issue by rehmke** [stormpath/stormpath-sdk-java#1121]
In conjunction with the Stormpath java servlet plugin (tested v1.1.4 and v1.1.5), it seems that the following property:

stormpath.web.logout.invalidateHttpSession = false

... is ignored if set to "false", as it seems that the session is destroyed once a post to the logout URI is made, regardless of the aforementioned configuration.

**Comment by dogeared** [comment]
Looking into this @rehmke

**Comment by rehmke** [comment]
Much appreciated, and I have seen numerous github notifications with regard
to the Stormpath java servlet codebase over the past few days.  In addition
to the LinkedIn fix last week, are there other related source updates that
we should procure?

**Comment by dogeared** [comment]
I've identified the problem and will put up a PR shortly. We are close to releasing the `1.2.0` version of the SDK, which has a number of bugfixes and additions. It will also include the fix for this issue.
