### ISSUE TITLE
Update all copyright notices to 2017

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#1197]
```
sed -i -e ’s/2016/2017/g’ index.html && \
git commit -am “new year in footer” && \
git push production master && \
say “Until next year”
```

**Comment by mrioan** [comment]
Hey @dogeared to the best of my understanding the copyright header is solely added when the file is created. We do not update them later on. New files (created in 2017) will have that year in the copyright.

**Comment by dogeared** [comment]
Closing per @omgitstom
