### ISSUE TITLE
Allow an Spring Security app to start even if a WebSecurityConfigurerAdapter is not defined

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#1238]
Currently, any app using our Spring Security integration requires a configuration file extending `WebSecurityConfigurerAdapter` to start. If it is missing the Spring Security's default configuration will override ours. That causes our Spring Security integration to break.

**Comment by mraible** [comment]
@mrioan This is the specific issue it causes: https://github.com/stormpath/stormpath-sdk-java/issues/1236
