### ISSUE TITLE
CORS support is broken in stormpath-default-spring-boot-starter in 1.3.0+

### ISSUE THREAD

**Issue by mraible** [stormpath/stormpath-sdk-java#1241]
Steps to reproduce:

1. git clone https://github.com/stormpath/stormpath-angularjs-access-control-cors-example
2. cd into the `stormpath-angularjs-access-control-cors-example` directory and run `mvn spring-boot:run`.
3. In another terminal window, cd into the same directory and run `npm i && gulp`. This will open your default browser and you should be able to login to the app.
4. Cancel the Maven command and upgrade to 1.3.1 by changing `pom.xml` to use version `1.3.1` for the `stormpath-default-spring-boot-starter` dependency. You'll also need to modify `SecurityConfiguration.java` to remove `http.apply(stormpath()`. [This PR](https://github.com/stormpath/stormpath-angularjs-access-control-cors-example/pull/1/files) shows both of these upgrade steps.
5. Run `mvn spring-boot:run` and try to login with the client again (you may have to delete cookies). 
6. You will see an error but the expected outcome is a successful login.

![screen shot 2017-01-17 at 2 54 17 pm](https://cloud.githubusercontent.com/assets/17892/22041638/def3c92a-dcc4-11e6-9f4c-de4d43e12735.png)

**Comment by mrioan** [comment]
@mraible I think I know what the problem is. When I press the login button I see this request:

 ```OPTIONS /login HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:49.0) Gecko/20100101 Firefox/49.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: es,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
origin: http://localhost:3000
Connection: keep-alive
````

This is not a post request, this is a preflight request. See what a preflight means: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

So, angular should be sending an actual POST request, not a preflight.

**Comment by mraible** [comment]
I'm able to workaround this issue by adding the following bean definition to a configuration class.

```java
    @Bean
    public CorsFilter corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("http://localhost:4200");
        config.addAllowedHeader("*");
        config.addAllowedMethod("*");
        source.registerCorsConfiguration("/**", config);
        return new CorsFilter(source);
    }
```
