### ISSUE TITLE
IDSIte callback is not open when "/" is closed

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#1254]
In Java SDK 1.4.0 if a user is using IDSite and they have a web config like this (note that "/" is closed):

```
    @Override
    protected void configure(HttpSecurity http) throws Exception {
    }
```

Then when IDSite does the callback the request never lands in the `IDSiteResultController` and a login loop takes place.

Workaround so far:

```
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeRequests()
            .antMatchers("/stormpathCallback").permitAll();
    }
```

It seems we are opening `idSiteResult` instead of `stormpathCallback`.

**Comment by mrioan** [comment]
It seems that this issue is a duplicate of https://github.com/stormpath/stormpath-sdk-java/issues/1236

**Comment by dogeared** [comment]
@mrioan - I don't believe this is a dup of #1236.
