### ISSUE TITLE
Support getSingle*() methods

### ISSUE THREAD

**Issue by chrylis** [stormpath/stormpath-sdk-java#127]
A number of methods (e.g., `getApplications()`) are frequently used to just select a single result (e.g., by name), but the methods all return `CollectionResource` objects. It would be helpful to have JPA-style `getSingle` methods (e.g., `client.getSingleApplication(criteria)`) that verified that exactly one item matches and return that single item.

Instead of:

    client.getApplications(Applications.where(Applications.name().eqIgnoreCase(stormpathInfo.getApplication()))).iterator().next();
    // plus sanity checks

just

    client.getSingleApplication(Applications.where(Applications.name().eqIgnoreCase(stormpathInfo.getApplication())));

**Comment by lhazlewood** [comment]
I like it - thanks for the suggestion!

**Comment by antollinim** [comment]
Hello @chrylis. We are going to add the `getSingle()` method to the `CollectionResource` interface. This will materialize this kind of operations:
```java
Application app = client.getApplications(Applications.where(Applications.name().eqIgnoreCase(stormpathInfo.getApplication()))).getSingle();
Account account  = application.getAccounts(Accounts.where(Accounts.username().eqIgnoreCase("test@stormpath.com"))).getSingle();
Group group = account.getGroups(Groups.criteria().withAccountMemberships(1, 0).and(Groups.name().endsWithIgnoreCase("X"))).getSingle();
Account account = directory.getAccounts(Accounts.surname().eqIgnoreCase("Doe")).getSingle();
```

The `getSingle()` method will throw when the list contains zero or more than one item.

Any thoughts?

**Comment by markwoon** [comment]
+1

**Comment by lhazlewood** [comment]
Ah, no, RC4 was released earlier today at 12 noon PST.  We could try to squeeze it into a follow up point release though.

**Comment by chrylis** [comment]
It's certainly an improvement!

**Comment by mrioan** [comment]
Implemented in https://github.com/stormpath/stormpath-sdk-java/pull/171
