### ISSUE TITLE
Rename com.stormpath.sdk.error.Error (JSDK-200)

### ISSUE THREAD

**Issue by chrylis** [stormpath/stormpath-sdk-java#129]
The name of the `com.stormpath.sdk.error.Error` interface duplicates a core class name from the `java.lang` namespace. I strongly recommend renaming it, perhaps to something like `StormpathError`.

**Comment by lhazlewood** [comment]
I don't have any objection to this - I think it's a good idea.  We'll have to do it right before releasing 1.0 final however since we can't change it after then.
