### ISSUE TITLE
X-Forwarded-Proto HTTP header

### ISSUE THREAD

**Issue by c-knowles** [stormpath/stormpath-sdk-java#139]
In the servlet plugin, please could you support the `X-Forwarded-Proto` HTTP header if SSL termination is offloaded to dedicated hardware? Typically this would be up to the HttpServletRequest.isSecure() call inside DefaultAccessTokenRequestAuthorizer, however this does not work across all containers and versions. Perhaps there is a nice generic way to solve it with another resolver.

**Comment by lhazlewood** [comment]
Hiya,

Isn't this covered by all containers?  For example, Tomcat has the [RemoteIpValve](https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/valves/RemoteIpValve.html) and Jetty supports this out of the box.

Thoughts?

**Comment by c-knowles** [comment]
I've had experience of this not being covered, but maybe those places can just use RemoteIpValue as you say. Perhaps it would be useful to clarify in the documentation that isSecure() is used and therefore what is needed to ensure it's working?

**Comment by lhazlewood** [comment]
We can definitely update the docs.  I'm also not against putting additional logic in the plugin if you think it would be better - I was just stating that I thought there were already solutions for this based on the container the app is deployed in.  If it's not obvious or not common, then we could do it for sure.  Any opinions?

**Comment by c-knowles** [comment]
I agree, it could go either way. I have less of a preference if it's mentioned in the docs. If this didn't work out of the box, should IsLocalhostResolver align to that? I saw X-Forwarded-For and the like are supported directly there which might be a reason to also include X-Forwarded-Proto support.

**Comment by lhazlewood** [comment]
Good point about existing `X-Forwarded-For` support.  I think it wouldn't hurt to have the `X-Forwarded-Proto` in there too then.

**Comment by dogeared** [comment]
@lhazlewood - Is this something we want for 1.0? Is it still relevant given the support for Spring Boot via application.properties?

**Comment by mrioan** [comment]
@lhazlewood thinks he already has this implemented in some branch of his. We might want to investigate it. Otherwise @mrioan does have a piece of code that has shared in a support ticket, so you can ask him.

**Comment by lhazlewood** [comment]
@mrioan was right - I didn't implement this in a branch.  I was thinking of the X-Forwarded-For support that I added to the `RemoteAddrResolver` (that does exist in master).

**Comment by dogeared** [comment]
confirmed that `X-Forwarded-For` is in `RemoteAddrResolver`.  Support for `X-Forwarded-Proto` would go somewhere else, I would imagine. Should we keep it as part of this issue or close this and create an issue specifically for `X-Forwarded-Proto`?

**Comment by dogeared** [comment]
Need to find all places where we are checking for secure connection required and take into account the `X-Forwarded-Proto` header. This should be written as a single component to to keep the code DRY.

**Comment by mraible** [comment]
What's the best way to test our implementation works as expected? It seems like it'd be easy enough to set the header as follows in `StormpathFilter#setRequestAttributes`. For example:

```java
protected void setRequestAttributes(HttpServletRequest request) {
    //ensure the Client and Application are conveniently available to all request filters/handlers:
    setClientRequestAttributes(request);
    setApplicationRequestAttributes(request);

    // set client headers on a thread local so they can be retrieved in DefaultDataStore
    Map<String, List<String>> headersMap = new LinkedHashMap<>();
    Enumeration<String> headerNames = request.getHeaderNames();
    while (headerNames.hasMoreElements()) {
        String name = headerNames.nextElement();
        // Tomcat returns all header names as lowercase. In case others don't, lowercase key name
        // http://grokbase.com/t/tomcat/users/0968njb9en/header-names-lower-case
        headersMap.put(name.toLowerCase(), Collections.list(request.getHeaders(name)));
    }

    // 139: Add X-Forwarded-Proto header
    headersMap.put("x-forwarded-proto", Collections.singletonList(request.getScheme()));

    HttpHeadersHolder.set(headersMap);
}
```
