### ISSUE TITLE
Additional User Agents for Java components

### ISSUE THREAD

**Issue by antollinim** [stormpath/stormpath-sdk-java#165]
- Stormpath Spring Boot
- Stormpath Java Servlet
- Spring boot

**Comment by lhazlewood** [comment]
Hi @antollinim, were you able to test this against the `spring` branch since that has all the dependencies you'd look for?

**Comment by antollinim** [comment]
Hey @lhazlewood. Yes, I have been playing with your branch in order to detect `Stormpath Spring Boot`. It is already working. I am seeking `com.stormpath.spring.boot.autoconfigure.StormpathAutoConfiguration` and outputting `spring-boot-starter-stormpath`. Is that ok for you?

**Comment by lhazlewood** [comment]
well, there are 4 environments where Spring is in play:

- traditional Spring (non web app)
- traditional Spring web app
- Spring Boot (non web app)
- Spring Boot Web App

Ideally, we should know which of those 4 are in play.

`StormpathAutoConfiguration` is in the classpath during both Spring Boot (non web app) and Spring Boot webapp deployments.

**Comment by antollinim** [comment]
These are current samples:
* `stormpath-sdk-java/1.0.RC4-SNAPSHOT stormpath-servlet-java/1.0.RC4-SNAPSHOT spring-boot-starter-stormpath/1.0.RC4-SNAPSHOT spring/4.1.3.RELEASE java/1.8.0_25 Mac OS X/10.10.2 (spring-boot/1.2.0.RELEASE tomcat/8.0)`
* `stormpath-shiro/0.7.0-SNAPSHOT stormpath-sdk-java/1.0.RC4-SNAPSHOT java/1.6.0_65 Mac OS X/10.10.2 (shiro/1.2.3 jetty/8.1.5.v20120716)`
* `stormpath-shiro/0.7.0-SNAPSHOT stormpath-sdk-java/1.0.RC4-SNAPSHOT java/1.8.0_25 Mac OS X/10.10.2 (shiro/1.2.3 wildfly/8.2.0.Final)`
* `stormpath-sdk-java/1.0.RC4-SNAPSHOT stormpath-servlet-java/1.0.RC4-SNAPSHOT java/1.8.0_25 Mac OS X/10.10.2`
* `stormpath-sdk-java/1.0.RC4-SNAPSHOT java/1.8.0_25 Mac OS X/10.10.2`

**Comment by lhazlewood** [comment]
I'm curious - why the parenthesis?  Why not just list those as normal space-delimited entries?

**Comment by antollinim** [comment]
During the first implementation I followed this: https://stormpath.atlassian.net/wiki/display/SDKS/User-Agent. `ANYTHING_ELSE` is surrounded by parentheses. I agree with you that it is not needed by any reason in particular, I just followed what was documented. I will remove that now.

**Comment by lhazlewood** [comment]
Also note that traditionally more generic things are listed later in the string, i.e. java/whatever would be last and spring-boot-starter-stormpath-thymeleaf/whatever might be first.

**Comment by antollinim** [comment]
Agreed, somehow top-down the stack...

**Comment by antollinim** [comment]
They look like this now:
* `stormpath-sdk-java/1.0.RC4-SNAPSHOT stormpath-servlet-java/1.0.RC4-SNAPSHOT spring-boot-starter-stormpath/1.0.RC4-SNAPSHOT spring/4.1.3.RELEASE spring-boot/1.2.0.RELEASE tomcat/8.0 java/1.8.0_25 Mac OS X/10.10.2` 
* `stormpath-spring-security/0.4-SNAPSHOT stormpath-sdk-java/1.0.RC4-SNAPSHOT spring-security/3.2.0.RELEASE spring/4.0.1.RELEASE tomcat/6.0 java/1.8.0_25 Mac OS X/10.10.2` 
* `stormpath-shiro/0.7.0-SNAPSHOT stormpath-sdk-java/1.0.RC4-SNAPSHOT shiro/1.2.3 wildfly/8.2.0.Final java/1.8.0_25 Mac OS X/10.10.2` 
* `stormpath-sdk-java/1.0.RC4-SNAPSHOT stormpath-servlet-java/1.0.RC4-SNAPSHOT java/1.8.0_25 Mac OS X/10.10.2` 
* `stormpath-sdk-java/1.0.RC4-SNAPSHOT java/1.8.0_25 Mac OS X/10.10.2`

**Comment by lhazlewood** [comment]
Looks good!  Minor note: stormpath extensions should be listed before stormpath-sdk-java (since they 'sit on top of' stormpath-sdk-java

Same principle for any other dependency.  If A depends on B, A is listed first then B, etc.

**Comment by lhazlewood** [comment]
Closing per the 1.0.RC4 release
