### ISSUE TITLE
Support OpenJDK 7

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#17]
A Java client using the Stormpath Java SDK on OpenJDK7 cannot connect to api.stormpath.com because (it appears) that OpenJDK7 does not recognize DigiCert's Extended Validation High Assurance Certificate Authority (CA).  This is quite surprising given that DigiCert is one of the world's top 5 CAs.

Perhaps this can be resolved by configuring the SDK's HttpClient configuration to recognize the CA:

http://javaskeleton.blogspot.com/2010/07/avoiding-peer-not-authenticated-with.html

It has been confirmed that the Oracle JDK 7 does not have any problems - that can be used as a workaround.

**Comment by gregorydickson** [comment]
This is a bit painful when using default Amazon AMIs that come with Open JDK. FYI. You have to create a custom AMI with Oracle JDK.

**Comment by lhazlewood** [comment]
@gregorydickson yeah, it's unfortunate that Amazon is dragging their feet on this. Oracle end-of-lifed all forms of JDK 7 a year an a half ago - I can't believe they haven't updated things yet!

**Comment by gregorydickson** [comment]
They have Java 8, but they have Open JDK 8, instead of Oracle JDK 8, which has the same issue with the Digicert CA.
