### ISSUE TITLE
Servlet Plugin ID Site support

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#172]
The Servlet plugin + the Spring WebMVC and Spring Boot WebMVC artifacts should have out-of-the-box support for ID site.

**Comment by lhazlewood** [comment]
This is being worked on in the [idsite branch](https://github.com/stormpath/stormpath-sdk-java/tree/idsite).

**Comment by lhazlewood** [comment]
PR #173 was merged.  This issue can't be closed until the same support works in the Servlet plugin as well.

**Comment by mraible** [comment]
@lhazlewood What needs to happen to enable ID Site support in the servlet plugin?
