### ISSUE TITLE
Move (never reviewed) IDSite branch from Spring Security to the Java SDK

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#178]
Although there was an IDSite branch in the standalone Spring Security Plugin (see [here](https://github.com/stormpath/stormpath-spring-security/tree/id_site)), it was never reviewed and merged into master. Now that the Spring Security code resides inside the Java SDK we need to move the IDSite code to the Java SDK.

**Comment by dogeared** [comment]
Is this still relevant? https://github.com/stormpath/stormpath-spring-security/compare/id_site

**Comment by mrioan** [comment]
@dogeared I am closing this as it is not relevant any longer, it was created a long time ago. It was about having Spring Security working with IDSite which we already have...
