### ISSUE TITLE
Add gradle install instructions to readme.md

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#187]
```gradle
repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile 'com.stormpath.sdk:stormpath-sdk-api:1.0.RC4.2'
    runtime 'com.stormpath.sdk:stormpath-sdk-httpclient:1.0.RC4.2'
}
```

This seems to be working correctly.  Can an engineer validate it and add it as an additional option to the quickstart?

**Comment by lhazlewood** [comment]
Just some notes:

You don't need to define the repositories in the `buildscript` block - that's only relevant if the build script itself needs to resolve build plugins in a specific way.  The following is the recommended practice:

```gradle
repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile 'com.stormpath.sdk:stormpath-sdk-api:1.0.RC4.2'
    runtime 'com.stormpath.sdk:stormpath-sdk-httpclient:1.0.RC4.2'
}
```

Note that the `httpclient` dependency is runtime only - SDK users should never be able to compile against that dependency (just use it at runtime) as implementations within it can experience backwards incompatible changes at any point without notice.  The same is true of the `impl` dependency.

Also note that in `repositories`, `mavenLocal()` is referenced before `mavenCentral()` - this ensures local disk is checked first for a dependency before having to go to the global central repository over the network.

**Comment by omgitstom** [comment]
Updated my comment - thanks!

**Comment by lhazlewood** [comment]
Also, do we want to add this to the readme?  Claire's format on the Readme is that users are directed to the quickstart which has the correct setup information.

Also note that, at least on the surface, I'm against adding this to the readme - it is yet *another* location to manually update every time we cut a release.

**Comment by omgitstom** [comment]
It has the correct setup information if you are using maven.  Gradle is not 100% clear.  You are having to modify the file anyways. AKA it is manual today, this change does not introduce a new manual step.  It is still a single step if you do a find / replace. Also, as soon as the quickstart is added to the test suite, we will be notified when an SDK change breaks the quickstart, so the quickstart can become static (resolve to LATEST, or lock it to the latest of v1). This isn't the first time, or the last time that we will have a customer ask for gradle installation instructions.

This is my input, I'm OK with this not going into the quickstart, but the quickstart isn't quick if you aren't using maven.

**Comment by lhazlewood** [comment]
This issue is specifically targeted at the `readme.md` file which we do not update during a release.

I'm saying it does makes sense to add this into the *quickstart* but *not* in the `readme.md` file, which you explicitly list in the issue title.

**Comment by dogeared** [comment]
We've had `build.gradle` files for a while now. I have created another issue to find a way to update the version automatically during deploy. The Maven deploy plugin does not touch build.gradle files (not surprisingly). See #526.
