### ISSUE TITLE
Fix Java Quickstart issues (JSDK-189)

### ISSUE THREAD

**Issue by maranai** [stormpath/stormpath-sdk-java#201]
This issue requires the following:
1) Run through the java quick start for completeness / correctness. Any deviation should be corrected in a PR to stormpath.github.io
2) Add the Java Quickstart code as a test that gets run for the Java SDK. This should live as it's own test that will validate that the quickstart will still work after any java SDK changes
3) I would like to have a full runnable (main method) java class that illustrates the items in the quickstart added to the java sdk repo that we can link to from the quickstart

**Comment by mrioan** [comment]
Released
