### ISSUE TITLE
Loading apiKeys from classpath: resource doesnt work

### ISSUE THREAD

**Issue by maxkremer** [stormpath/stormpath-sdk-java#206]
I'm trying to load the api keys like so:

```
ApiKey apiKey  =ApiKeys.builder().set("classpath:stormpathkeys.properties").build();
```

Causes

```
java.lang.IllegalArgumentException: Unable to read properties from specified apiKeyFileLocation [classpath:stormpathApiKey.properties].
	at com.stormpath.sdk.impl.api.ClientApiKeyBuilder.build(ClientApiKeyBuilder.java:220)
```

This used to work in version 0.8 of the api

**Comment by lhazlewood** [comment]
Shouldn't it be the following?

```java
ApiKey apiKey  = ApiKeys.builder().setFileLocation("classpath:stormpathkeys.properties").build();
```

**Comment by lhazlewood** [comment]
Also, something feels weird - the exception message references a location of `classpath:stormpathApiKey.properties` but your code example references `classpath:stormpathkeys.properties`

**Comment by maxkremer** [comment]
Sorry my bad, a few typos in the example code. It should say:
```
ApiKey apiKey = ApiKeys.builder().setFileLocation("classpath:stormpathApiKey.properties").build();
```
and
```
java.lang.IllegalArgumentException: Unable to read properties from specified apiKeyFileLocation [classpath:stormpathApiKey.properties]
```

I've also confirmed that if I specify the location via file path it works fine.
```
//This works
ApiKey apiKey  =ApiKeys.builder().setFileLocation("/home/max/rest-play/conf/stormpathApiKey.properties").build();
```

**Comment by maxkremer** [comment]
I took a look at the source and it looks like the `ClientApiKeyBuilder` makes use of the `FileResource` but I can't find any logic that uses the `ClasspathResource`.

It appears there is a `DefaultResourceFactory` which seems to be responsible for deciding which type of resource to create (URL, File or Classpath) but it doesn't seem to be used anywhere.

**Comment by maxkremer** [comment]
@lhazlewood have you had a chance to confirm this bug?

**Comment by mrioan** [comment]
@maxkremer I have just tried this and it works:

`ApiKey apiKey = ApiKeys.builder().setFileLocation("stormpathApiKey.properties").build();`

*Note the missing `classpath:` prefix.

Can you please confirm that it works for you?

**Comment by maxkremer** [comment]
No that doesn't work. 

```
java.lang.IllegalArgumentException: Unable to read properties from specified apiKeyFileLocation [stormpathApiKey.properties].
	at com.stormpath.sdk.impl.api.ClientApiKeyBuilder.build(ClientApiKeyBuilder.java:220)

```

**Comment by mrioan** [comment]
@maxkremer in a first test, the `apikey` was automatically read from my home folder. I thought it was working but you are right, there is a bug indeed.

This will need to be fixed in a new release. Tentative solution could be:

In `ClientApiKeyBuilder.java`:

    protected Reader createFileReader(String apiKeyFileLocation) throws IOException {
        InputStream is = null;
        if (apiKeyFileLocation.startsWith("classpath:")) {
            is = new ClasspathResource(apiKeyFileLocation).getInputStream();
        }
        //Defaults to a file resource
        if (is == null) {
            is = new FileResource(apiKeyFileLocation).getInputStream();
        }
        return toReader(is);
    }

**Comment by lhazlewood** [comment]
I just realized something - why is the api key in the classpath?

That typically means the api key is checked in to source control and built/packaged with the project that uses Stormpath.  API Keys should never be checked in to source control as they would be visible to other developers.

Or is there a different use case for an api key to be in the classpath that I'm missing?  Any information would be helpful for us to understand the use case.  Thanks!

**Comment by maranai** [comment]
I have reviewed the PR and it's approved in case you make the decision to apply this change.

**Comment by maxkremer** [comment]
@lhazlewood regarding the api key being in the classpath. In our particular case the build process swaps out the dev api key file with a prod api key file. The prod api key file is not in version control. In any case the built JAR contains a key file which is accessed via classpath from inside the running app.

**Comment by dogeared** [comment]
Closing this issue as the solution was merged back in October.
