### ISSUE TITLE
[Servlet Plugin] Non-root Context Issues

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#210]
1. `spring-webmvc example`: after `login`, the user is redirected to the root context. The app is not running in this uri and thus the user gets `Error 404 - Not Found`
2. `spring-webmvc example`: after `logout`, the user is redirected to the root context (e.g `http://localhost:8080/login?status=logout`). The app is not running in this uri and thus the user gets `Error 404 - Not Found`
3. `spring-boot-webmvc example`: Spring boot can be configured to run in the non-root context path just by adding something like this in `resources/application.properties`: `server.contextPath=/myAppContextPath`. The Spring boot example will run in `http://localhost:8080/myAppContextPath` but the Servlet plugin will return to the root context after `login` and `logout`

**Comment by dogeared** [comment]
@mrioan - should this be in 1.0?

**Comment by lhazlewood** [comment]
*.uri config properties should be context-relative - not sure why the current behavior occurs.

**Comment by mraible** [comment]
I tried to reproduce this today and here's what I found:

1. In `examples/spring-webmvc/pom.xml`, I changed the tomcat7-maven-plugin to have `<path>/foo</path>` for the contextPath. I logged in and was redirected to http://localhost:8080/foo/, which proves this is no longer an issue with `spring-webmvc`.
2. Logout also takes me to http://localhost:8080/foo/, so this is no longer an issue.
3. I added `/Users/mraible/dev/stormpath-sdk-java/examples/spring-boot-webmvc/src/main/resources/application.properties` and ran `mvn spring-boot:run`. I was able to login and logout without issues.

@dogeared @lhazlewood I believe you can close this issue.
