### ISSUE TITLE
Criteria with non-standard chars fails to compare properly

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#215]
The `Directories.name()` string expression leading to the `Criterion` build, generates a `Criterion` that cannot compare non-standard strings. 

Assuming: 
String directoryId = "易安信电脑"; 
The following code doesn't work (exact match criterion): 
```
DirectoryList directoryList = application.getTenant().getDirectories(Directories.where(Directories.name().eqIgnoreCase(directoryId)));
```

Returns an empty list when the Backed does have a directory named "易安信电脑".

The following code (full iteration) works: 
```
Iterator<Directory> iterator = directoryList.iterator(); 
while (iterator.hasNext()) { 
    Directory directory = iterator.next(); 
    if (directory.getName().equals(directoryId)) 
    ...
```

**Comment by lhazlewood** [comment]
Is this limited to just the Java SDK? Or does it also happen when using cURL or httpie?

**Comment by dogeared** [comment]
@mrioan @lhazlewood - I've confirmed that this issue occurs from the command-line using `curl`.

Assuming I have two directories with the following names:

```
MyDirA
a易安信电脑z
``

`curl -u $STORMPATH_API_KEY_ID:$STORMPATH_API_KEY_SECRET https://api.stormpath.com/v1/tenants/$STORMPATH_TENANT_ID/directories`

returns a JSON response that includes the `a易安信电脑z` directory.

`curl -u $STORMPATH_API_KEY_ID:$STORMPATH_API_KEY_SECRET https://api.stormpath.com/v1/tenants/$STORMPATH_TENANT_ID/directories?name=MyDirA`

returns a JSON response that includes the directory information for `MyDirA`.

`curl -u $STORMPATH_API_KEY_ID:$STORMPATH_API_KEY_SECRET https://api.stormpath.com/v1/tenants/$STORMPATH_TENANT_ID/directories?name=a易安信电脑z`

returns an empty list:

```
{"href":"https://api.stormpath.com/v1/tenants/6umsSOCacld636fmeHLifk/directories","offset":0,"limit":25,"size":0,"items":[]}
```

Perhaps this should be an issue for the backend?

**Comment by lhazlewood** [comment]
Chinese characters (and other language characters) are not URL safe - you can't add them directly to a URL and have them work.

Do you know if cURL automatically URL-encodes before sending the request?

**Comment by lhazlewood** [comment]
Yep, need to use `-G` to url encode:

http://unix.stackexchange.com/questions/86729/any-way-to-encode-the-url-in-curl-command

**Comment by dogeared** [comment]
Fair enough. However,

```
curl -G -u $STORMPATH_API_KEY_ID:$STORMPATH_API_KEY_SECRET \
https://api.stormpath.com/v1/tenants/$STORMPATH_TENANT_ID/directories \
--data-urlencode "name=a易安信电脑z"
```
*still* returns an empty lists

whereas:

```
curl -u $STORMPATH_API_KEY_ID:$STORMPATH_API_KEY_SECRET \
https://api.stormpath.com/v1/tenants/$STORMPATH_TENANT_ID/directories
```

has a result that includes the `a易安信电脑z` directory.

Should this be logged as a backend issue?

**Comment by lhazlewood** [comment]
If that doesn't work, then yes, please open a backend issue.

**Comment by dogeared** [comment]
Resolved in latest backend release.
