### ISSUE TITLE
Regression 1.0.RC4.2 -> 1.0.RC4.3

### ISSUE THREAD

**Issue by francisdb** [stormpath/stormpath-sdk-java#216]
Our performance tracking system (ruxit) reports a serious degradation (+150ms/request) when we switch from 1.0.RC4.2 to 1.0.RC4.3

The main culprit seems to be a request to /v1/applications/xxx/apiKeys that is done for almost all requests.

Is this a known issue?

**Comment by omgitstom** [comment]
Hi @francisdb 

Thanks for logging this. This release contains collection caching optimizations so I am surprise that you are seeing a degradation.  SDK Caching should be turned on by default for apiKeys.  A couple of questions for you:

+ Are you configuring the Stormpath SDK client / cache manager any differently?  Or was switching the SDK version the only modification?  If you are configuring the cache manager, can you share your config?
+ If you roll back your changes (to version RC4.2), does the performance problem go away?  Or does the problem still exist?

My initial thought is that when you upgraded and restarted that the cache is starting over fresh, so it is cold, on additional requests it will become warm again and the amount of calls to the Stormpath API will be reduced.

Looking forward to the information and get to the bottom of this with you.

Thanks!
Tom

**Comment by francisdb** [comment]
Only version change, rollback to previous version fixed degradation
Ruxit reported 96.5 requests/min affected for 2 hours 28 minutes, that can hardly be a cold cache issue.

**Comment by francisdb** [comment]
we have a specific cachemanager where we also store account groups:
```java
// cache docs here: http://docs.stormpath.com/java/product-guide/#caching
        CacheManager cacheManager = Caches.newCacheManager()
                .withCache(Caches.named(GROUP_NAMES_CACHE)
                        .withTimeToLive(1, TimeUnit.HOURS)
                        .withTimeToIdle(30, TimeUnit.MINUTES))
                .build();
        // 
        CacheManager loggingCacheManager = new LoggingCacheManager(cacheManager);
        this.client = Clients.builder()
                .setApiKey(apiKey)
                .setCacheManager(loggingCacheManager)
                .build();
```

the LoggingCacheManager is a small extension I used before for debugging

```java
private static class LoggingCacheManager implements CacheManager {
        private static final Logger log = LoggerFactory.getLogger(LoggingCacheManager.class);

        private final CacheManager manager;

        public LoggingCacheManager(final CacheManager manager) {
            this.manager = manager;
        }

        @Override
        public <K, V> Cache<K, V> getCache(String name) {
            log.trace("Cache request for {}", name);
            return new LoggingCache<>(name, manager.getCache(name));
        }
    }
```

**Comment by omgitstom** [comment]
Hey @francisdb thanks, I wanted to make sure that we aren't missing anything.  This is great information.  Forgot one question though.

Do you have the code that is being called to invoke the REST call to /v1/applications/:appId/apiKeys?
Are you doing a app.authenticateApiRequest call or are you calling app.getApiKey(id)?

Thanks!
Tom

**Comment by francisdb** [comment]
We use authenticateApiRequest:

```java
StormPathAuthHeaderRequest request = new StormPathAuthHeaderRequest(authorizationHeader);
        try {
            OauthAuthenticationResult authResult = stormPath.getApplication()
                    .authenticateOauthRequest(request)
                    .withTtl(TOKEN_TTL)
                    .execute();
            Account account = authResult.getAccount();

            ApiKey apiKey = authResult.getApiKey();
            //HttpRequest tokenRequest = Utils.loggingProxy(HttpRequest.class, new StormPathTokenRequest(apiKey), log);
            HttpRequest tokenRequest = StormPathAuthHeaderRequest.fromApiKey(apiKey);

            ApiAuthenticationResult result = stormPath.getApplication().authenticateApiRequest(tokenRequest);
            if(result instanceof AccessTokenResult) {
                AccessTokenResult accessTokenResult = (AccessTokenResult) result;

                //Get the token response from the result which includes
                //information about the Access Token
                TokenResponse tokenResponse = accessTokenResult.getTokenResponse();

                Instant expires = Instant.now().plusSeconds(Long.valueOf(tokenResponse.getExpiresIn()));
                Token token = new Token(
                        tokenResponse.getAccessToken(),
                        tokenResponse.getTokenType(),
                        expires);
...
```

**Comment by omgitstom** [comment]
Seems like API Key caching is not enabled in RC4.3 - Below is the output from my test runs:

1.0.RC4.3: 2768
Number of API Keys Tested: 18
1.0.RC4.3: 2456
Number of API Keys Tested: 18
1.0.RC4.3: 2580
Number of API Keys Tested: 18

1.0.RC4.2: 2740
Number of API Keys Tested: 18
1.0.RC4.2: 82
Number of API Keys Tested: 18
1.0.RC4.2: 89
Number of API Keys Tested: 18

@mrioan @josebarrueta can you guys validate/fix this and make sure we have tests written around this to validate that the caching of API keys isn't modified during development?

**Comment by josebarrueta** [comment]
@mrioan can you please review this PR? should be pretty quick. Thanks.

**Comment by lhazlewood** [comment]
Successful PR for this has been merged to master.
