### ISSUE TITLE
Simplifying our account/group methods for associations with groups and account

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#220]
Extend our account and group resources to make management of associations easier.

Introduce functionality for:

Groups:
Adding an account to a group
Removing an account to a group
Checking if a group has account or accounts

Accounts:
Adding a group to an account
Removing a group to an account
Checking if a account has group or groups

The methods will accept the following:
a group/account object
a group/account href
a group name or account email / username

**Comment by maranai** [comment]
Documentation changes PR: https://github.com/stormpath/stormpath.github.io/pull/178/commits

**Comment by maranai** [comment]
PR with code changes ready for review: https://github.com/stormpath/stormpath-sdk-java/pull/258

**Comment by mrioan** [comment]
Released
