### ISSUE TITLE
Custom Data Search

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#221]
Depends on AM-2100

**Comment by tomekl007** [comment]
Hi, need that feature in our app. Is there possibility to implement it in near future ?

**Comment by omgitstom** [comment]
https://stormpath.atlassian.net/wiki/display/AM/Custom+Data+Search

**Comment by markwoon** [comment]
+1

**Comment by omgitstom** [comment]
@dogeared mind replying to this?  This is something that we will add after 1.0, but it is possible with today's SDK

**Comment by dogeared** [comment]
Hey @markwoon - this has been integrated into the Java SDK and will be in the 1.0 release. For reference, #631 resolves this issue.

**Comment by mrioan** [comment]
@tomekl007 @markwoon. Although we still need to add a type-safe implementation Custom Data Search is already working (I.e. previous releases) out of the box using the Map Criteria:

```
Map<String, Object> criteria = new HashMap<String, Object>();
criteria.put("customData.FavoriteColor", "Blue");
AccountList accounts = dir.getAccounts(criteria);
```

IMPORTANT NOTE: So far Custom Data Search is only available for `Accounts` via the `Directory` resource.
