### ISSUE TITLE
Request Builder - simplify the HTTP builder so you dont have to deal with maps

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#225]
HttpRequestBuilder builder = HttpRequests.method(HttpMethod.POST);

builder.header(String, String[]);
builder.parameter(String, String[]);

**Comment by maranai** [comment]
PR with code changes for this issue: https://github.com/stormpath/stormpath-sdk-java/pull/233/files

**Comment by mrioan** [comment]
Solved in #233
