### ISSUE TITLE
AuthC for APIs in Spring Security

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#226]
How can we make this feature really easy to use from Spring Security?

**Comment by mrioan** [comment]
What needs to happen here:

1. A Spring Sec application should be able to provide an Access Token: this should be already supported by the Servlet Plugin but we should validate that Spring Security is not somehow hindering that.
1.1. The Java SDK does not yet support the new Oauth Rest endpoint, so Spring Security will not provide that either.
2. A user must be considered "authenticated" when a request containing a valid access token is seen by Spring Security. This way, developers can use the Spring Security configuration to restrict access to their resources. This must be implemented, I guess we will need some Filter to create the Authentication and store it in the SecurityContext.
2.1. Additionally we should add a specific role for these kind of authorized requests (differentiating them from a regular user login)
2.2. We need to investigate how to use scopes, maybe each scope must be mapped to a role.
3. I guess we need to disable any kind of Spring Security session for Oauth authentications.

**Comment by dogeared** [comment]
Already addressed via Spec. Compliance.
