### ISSUE TITLE
Add documentation to highlight different configuration options for Spring Security

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#227]
Feedback from Customer
"I have noticed that the documentation on Stormpaths spring security git hub project is out of date, and although I've already figured it out, it would be good for others to have examples of spring security & Stormpath in context of Spring Boot, particularly the programmatic / annotation based configuration, which is a lot more elegant than the Xml examples provided. I can send my examples if you need"
I would like someone to review the Spring Security documentation on github to make sure it is correct. We have customers using different mechanisms to install stormpath and we need to highlight the steps for:

+ XML Config
+ Java Config
+ Spring Boot

**Comment by mrioan** [comment]
Released
