### ISSUE TITLE
Password Import MCF Feature

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#231]
http://docs.stormpath.com/rest/product-guide/#create-an-account-with-an-existing-password-hash

**Comment by maranai** [comment]
PR: https://github.com/stormpath/stormpath-sdk-java/pull/236

**Comment by mrioan** [comment]
@maranai I have unassigned myself from this until I can work on it.

**Comment by mrioan** [comment]
Solved in #236
