### ISSUE TITLE
Support for stormpath-angular

### ISSUE THREAD

**Issue by myspivey** [stormpath/stormpath-sdk-java#235]
https://docs.stormpath.com/angularjs/guide/protect_api.html

Details how the Express API supports middleware for endpoints, currently as best I understand, the java SDK does not. Is this something that can or might be added in the future?

**Comment by mrioan** [comment]
@myspivey I am not sure there is a 1:1 mapping between that in Express and Java. Could you please give an example of what you would specifically like to see in Java's context?

**Comment by omgitstom** [comment]
@mrioan Right now the angular SDK only supports one of the stormpath backends (express angular) and this is something that we need to support for all our integrations across all of the languages.

Stormpath has taken the approach to get the integrations out to test each community to figure out where which communities feel the demand for a product like Stormpath.  Now we are moving towards unifying all of the integrations to expand to make sure we can support the client libraries.

So @myspivey the answer is yes.  We are actually finalizing the spec work https://github.com/stormpath/stormpath-framework-spec and will be modifying all of the framework integrations to support similar endpoints.   Out of curiosity, are you using a particular framework (like Spring) or just looking at using the Java SDK?  If you are using the Java SDK, we could possibly provide guidance around which 'endpoints' you would need to expose and what you would need to return through those endpoints.

**Comment by myspivey** [comment]
Currently using Spring Boot implemented through http://jhipster.github.io/. Front end is Angular so would be great to use the current Angular library, however as noted, that is only supported by Express. We are currently using their OAuth2 implementation with the hopes of integrating and replacing this with Stormpath.

**Comment by dogeared** [comment]
our upcoming 1.0 release will be fully [spec compliant](https://github.com/stormpath/stormpath-framework-spec) and the [Stormpath AngularJS SDK](https://github.com/stormpath/stormpath-sdk-angularjs) will work against the Java SDK.
