### ISSUE TITLE
Application#sendPasswordResetEmail should return a PasswordResetToken rather than an Account

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#237]
The backend returns such resource, not an `Account`.

The issuer of the command loses the ability to get the generated token.

Note: This change will break current developer's code as the signature of the interface will change.

**Comment by maranai** [comment]
PR with documentation changes: https://github.com/stormpath/stormpath.github.io/pull/174

**Comment by maranai** [comment]
PR is ready for review:
https://github.com/stormpath/stormpath-sdk-java/pull/243

**Comment by mrioan** [comment]
Solved in #243
