### ISSUE TITLE
Get a resource based on a href fragment

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#238]
For example:

client.getDataStore().getResource('/applications/3QIMlJKKN2whGCYzXXw1t8', Application.class);

This should resolve to getting the object based on the baseUrl when building the client, similar to making the call to:

client.getDataStore().getResource('https://api.stormpath.com/v1/applications/3QIMlJKKN2whGCYzXXw1t8', Application.class);

or

client.getDataStore().getResource('https://enterprise.stormpath.io/v1/applications/3QIMlJKKN2whGCYzXXw1t8', Application.class);

**Comment by maranai** [comment]
Product guide has been updated to mention the ability to load resources using a fragment of the href.
PR is ready for review:
https://github.com/stormpath/stormpath.github.io/pull/175/files
