### ISSUE TITLE
Rename spring-boot-starter-* modules

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#239]
The Spring team has asked that all non-Pivotal-managed releases *not* start with the prefix `spring-boot-starter-`.

Right before 1.0 final, we need to rename the following modules:

`spring-boot-starter-stormpath`: rename to `stormpath-spring-boot-starter`
`spring-boot-starter-stormpath-thymeleaf`: rename to `stormpath-thymeleaf-spring-boot-starter`
`spring-boot-starter-stormpath-webmvc`: rename to `stormpath-webmvc-spring-boot-starter`

As well as any other modules that aren't currently listed (spring security, etc)

**Comment by mrioan** [comment]
Released
