### ISSUE TITLE
Spring and Spring Boot related ITs cannot be configured to use another backend

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#246]
All ITs use the `Client` instantiated in `ClientIT` so they all can be configured to use other backends (instead of hitting `api.stormpath.com`). This is not true for Spring and Spring Boot ITs, these ITs always hit `api.stormpath.com`

**Comment by dogeared** [comment]
Action: confirm that STORMPATH_BASEURL will work with the client builder.

**Comment by mrioan** [comment]
This issue can be closed. STORMPATH_BASE_URL is actually working fine for these ITs
