### ISSUE TITLE
Document difference between "status" and "code" in ResourceException

### ISSUE THREAD

**Issue by chrylis** [stormpath/stormpath-sdk-java#254]
Is `status` the HTTP status code and `code` the value from http://docs.stormpath.com/errors/?

**Comment by dogeared** [comment]
Hey @chrylis:

First off, apologies for the (very) late reply here. We have put a process in place whereby we will respond to github issues within 48 hours.

Secondly, you are exactly correct. `status` is the HTTP status and `code` is from http://docs.stormpath.com/errors/
