### ISSUE TITLE
Spring Security: allow AccountStore to be specified during authentication

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#257]
We should allow an authentication to be triggered to a specific `accountStore` when using Spring Security.

Our Java SDK provides this:
```
UsernamePasswordRequest authenticationRequest = new UsernamePasswordRequest("usernameOrEmail", "password", accountStore);
```
but our Spring Security plugin does not expose the `accountStore`.

**Comment by lhazlewood** [comment]
There is an `AccountStoreResolver` that can be configured by the end-user.  The `ForgotLoginController` already uses it - we need to have the `LoginController` use it too I think.

**Comment by mrioan** [comment]
Closing as this is already supported
