### ISSUE TITLE
Organization Resource

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#260]
Internal link to the REST issue AM-2760

Internal link to the spec:
https://stormpath.atlassian.net/wiki/display/AM/Organization+Resource

**Comment by maranai** [comment]
Documentation for the Java SDK is pending. When REST API documentation is ready, I will update the product guide for  the JSDK.

**Comment by maranai** [comment]
Organization resource documentation PR:
https://github.com/stormpath/stormpath.github.io/pull/212
