### ISSUE TITLE
[Servlet] JWT `ttl` is overflowing  

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#262]
In `DefaultAuthenticationJwtFactory` the `ttl` variable is overflowing if `stormpath.web.account.jwt.ttl` is greater than `2147483` (24.8 days). This is the place where the problem exits:

        int ttl = getJwtTtlSeconds(request, response, result);
        if (ttl >= 0) {
            long ttlMillis = ttl * 1000; //JWT requires times to be in seconds (not millis) since epoch
            long expMillis = nowMillis + ttlMillis;
            Date exp = new Date(expMillis);
            builder.setExpiration(exp);
        }

If we use `long` we will have a such a huge `ttl` that it should never overflow (106751991167.3 days)

**Comment by maranai** [comment]
Fix for this bug in PR https://github.com/stormpath/stormpath-sdk-java/pull/374
