### ISSUE TITLE
Shut down stormpath-spring-security-example & stormpath-spring-security repo

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#266]
All the content from https://github.com/stormpath/stormpath-spring-security-example and  https://github.com/stormpath/stormpath-spring-security will be integrated into this release.

As such, the existing repo's files should be deleted, except for a `README.md` that points to the stormpath-sdk-java repo

https://github.com/stormpath/stormpath-spring-security/pull/21
https://github.com/stormpath/stormpath-spring-security-example/pull/18

**Comment by mrioan** [comment]
I think we also need to do the same with https://github.com/stormpath/stormpath-spring-security and https://github.com/stormpath/stormpath-spring-security-example

**Comment by dogeared** [comment]
Yes! I put in the wrong repo. The other one is actually current and will be tied to my Spring Boot / Spring Web MVC / Spring Security article.

**Comment by dogeared** [comment]
This is complete.
