### ISSUE TITLE
Remove JDK 1.6 and 1.7 support

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#270]
1.6 compatibility is hindering servlet 3.1 support and has been *long* end-of-lifed by now.  1.7 was end-of-lifed 4 months ago (April 2015) and will be EOL longer by the time we ship the SDK 1.0 final.

JDK 1.8 will be the minimum JDK version moving forward on and after 1.0 final.

**Comment by dogeared** [comment]
We've removed jdk 1.6 support in the latest version of `master`. We've decided to continue to support jdk 1.7 for the 1.0 release.
