### ISSUE TITLE
Ensure Java SDK and Integrations adhere to the respective Stormpath specifications

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#287]
SDK Spec: https://github.com/stormpath/stormpath-sdk-spec
Framework/Integration Spec: https://github.com/stormpath/stormpath-framework-spec

**Comment by dogeared** [comment]
As part of this, we want to make sure we address the issue that the node/express team experienced when implementing social logins:

- 2 cookies get set: access and refresh token. that allows clients to be able to call into protected api with access tokens
- social doesn't support the ability to create a stormpath oauth token
- express team is handling it by:
        - when they get the result, they package it up as a stormpath token and make a new request grant_type=stormpath_token
        - in order to get back an oauth tokens: access and refresh
        - https://github.com/stormpath/express-stormpath/issues/251

**Comment by dogeared** [comment]
This has been covered by many other issue and PRs. The TCK ensures that all framework spec elements are implemented.
