### ISSUE TITLE
Exchanging ID Site token for a Stormpath Access Token

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#292]
https://stormpath.atlassian.net/wiki/display/AM/ID+Site+OAuth+Access+Token+Grant+Type

**Comment by omgitstom** [comment]
Open question here from Support:

How does this feature effect customers developing against:
stormpath-shiro-servlet-0.7.1-idsite 
stormpath-shiro-core-0.7.1-idsite

Is there any code changes / configuration needed to take advantage of using access tokens?

**Comment by maranai** [comment]
Related PR (https://github.com/stormpath/stormpath-sdk-java/pull/436) needs to be reviewed. I has been updated to modify the grant_type as per Les' comment.

**Comment by dogeared** [comment]
closes #436
