### ISSUE TITLE
Integration support for multi-tenant ID Site

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#300]
While IdSiteUrlBuilder already has methods in the master branch for `setOrganizationNameKey`, `setUseSubdomain` and `showOrganizationField`, the servlet & Spring/Spring Boot integrations do not yet make use of these.

**Comment by lhazlewood** [comment]
The ID Site Result controller still needs to be updated:

If the user was on an application subdomain when they were redirected to ID site, they need to be returned to the same subdomain after coming back from ID Site.  Because all ID Site callbacks need to be whitelisted, dynamic (tenant-specific) subdomains cannot be pre-registered.  So the callback handler needs to do the redirect after ID Site return (i.e. probably look in the ID SIte jwt response and find the original subdomain and redirect based on that).

**Comment by lhazlewood** [comment]
(note to self:  when sending the user off to ID Site, we can probably use the `state` field on IdSiteUrlBuilder to retain the subdomain in effect and look at that in the result controller).

**Comment by lhazlewood** [comment]
@dogeared Have you had a chance to test things with the callback URL?  I don't think it would work if it is a subdomain (https://foo.bar.com).

**Comment by lhazlewood** [comment]
I believe this issue to be blocked until we allow wildcard domains to be registered as ID Site Authorized Redirect URIs - 'using up' the state attribute is not an effective long term solution, and it puts unnecessary implementation burden on all Stormpath SDK development teams.

**Comment by mrioan** [comment]
@dogeared Is this issue really solved? I am not sure about that. If so, could  you please reference the PR that solves this issue here? Otherwise this issue would needs to be re-open.

**Comment by lhazlewood** [comment]
I reopened per my last comment:

> I believe this issue to be blocked until we allow wildcard domains to be registered as ID Site Authorized Redirect URIs - 'using up' the state attribute is not an effective long term solution, and it puts unnecessary implementation burden on all Stormpath SDK development teams.

**Comment by dogeared** [comment]
Sorry - I confused this issue with the multi-tenant work you did in advance of the conference. My bad.

**Comment by lhazlewood** [comment]
We can close this - the remaining work is only in IAM and the SDK does not need to be updated when that is fixed.
