### ISSUE TITLE
Add support for LinkedIn provider to accept redirectUrl, and "code" during token exchange.

### ISSUE THREAD

**Issue by josebarrueta** [stormpath/stormpath-sdk-java#306]

**Comment by dogeared** [comment]
@josebarrueta @mrioan - has this been addressed by: https://github.com/stormpath/stormpath-sdk-java/commit/8d4c519c123b4a5172502698b4e3c69e6114809a ? If so, I'll close this issue.

**Comment by dogeared** [comment]
Closing as #1037 should address this.
