### ISSUE TITLE
Add a configuration property to disable Spring Security

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#308]

**Comment by lhazlewood** [comment]
What is this for?  You can already do stormpath.spring.security.enabled = false as a property.  Look at the `StormpathSpringSecurityAutoConfiguration` class.

I'm probably missing something, but I hope you can elaborate here.

**Comment by mrioan** [comment]
Yeap, we know about that property but, to the best of my understanding, it was actually never tested. I just tested it and it does not work out of box. It throws an exception. I have already fixed it in my local branch but now I am wondering what does "Disabling Stormpath Spring Security" actually means. In my mind it means that anything provided by Stormpath in regards to Spring Security should not be available any longer. This includes: login and logout functionality, Stormpath as authentication Realm, permission evaluation, disable pre-defined access `register`/`forgot`/`verify`/etc pages. Thoughts?

**Comment by lhazlewood** [comment]
In my mind, it just disables the Spring Security-specific components.  If you want to disable all that other stuff, you'd do `stormpath.web.disabled`.

**Comment by mrioan** [comment]
Ok, so...

1. `stormpath.spring.security.enabled = false` will disable: Stormpath as authentication Realm and permission evaluation
2. `stormpath.web.enabled = false` will disable: login and logout functionality + all the pre-defined pages.

**Comment by lhazlewood** [comment]
Yep!

1.  If `stormpath.spring.security.enabled = false` then *only* the Stormpath Spring security components should be disabled.

2.  If `stormpath.web.enabled = false` then all Stormpath web functionality, including Stormpath Spring Security Web components (but *not* non-web Stormpath Spring Security components) should be disabled.

3.  If `stormpath.enabled` = false then all Stormpath components should be disabled.

**Comment by mrioan** [comment]
Solved in #304

**Comment by mrioan** [comment]
Solved in #304
