### ISSUE TITLE
*really* disable Spring Security

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#319]
When the setting:

```
stormpath.spring.security.enabled = false
```

is present in `application.properties`, the Stormpath Spring Security hooks are properly disabled. 

However, Spring Security Core is still loaded as evidenced by the `springSecurityFilterChain` being loaded in the startup logs.

```
2015-10-27 15:02:32.148  INFO 54463 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'springSecurityFilterChain' to: [/*]
```

The result is that you get the default basic authentication popup when the intention is to disable Spring Security.

A workaround would be to set:

```
security.ignored=/**
```

But, it would be better to not load - or unload the `springSecurityFilterChain`

**Comment by lhazlewood** [comment]
I believe the correct behavior is already exhibited.

`stormpath.spring.security.enabled` is only supposed to turn off *Stormpath*'s spring security support.

A user of Spring Security should disable it in the way that is documented by Spring Security, presumably via a `spring.security.enabled = false` config line or commenting out an annotation, or something similar.

**Comment by dogeared** [comment]
For the purpose of being complete here and per @lhazlewood's comment above, we can use:

`security.basic.enabled = false` in conjunction with `stormpath.spring.security.enabled = false` to effectively disable Spring Security when using the `stormpath-default-spring-boot-starter`
