### ISSUE TITLE
Normal Spring behavior described as being Stormpath specific magic

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/stormpath-sdk-java#321]
In the Stormpath [Spring Boot Web tutorial](http://docs.stormpath.com/java/spring-boot-web/tutorial.html) it says at one point:

> Now for the Stormpath magic. You can also have a system environment variable named STORMPATH_AUTHORIZED_GROUP_USER. Behind the scenes, Stormpath will convert that system environment variable to a Spring environment variable named stormpath.authorized.group.user.

Isn't this just normal Spring behavior rather than Stormpath magic? If I step into the logic involved I end up in [`org.springframework.core.env.SystemEnvironmentPropertySource.resolvePropertyName(String)` ](https://github.com/spring-projects/spring-framework/blob/587a816/spring-core/src/main/java/org/springframework/core/env/SystemEnvironmentPropertySource.java#L103) and it's this that works out that something like `stormpath.authorized.group.user` can be mapped to an all caps environment variable with underscores rather than periods.

Anyway it's a minor niggle - I'm working my way through the tutorial and it all looks like a great improvement on the alternatives :smile:

**Comment by dogeared** [comment]
Right you are @george-hawkins-aa. I was fairly new when I wrote the tutorial and mistakingly thought it was our `EnvVarNameConverter` that was doing the trick. We use that in our servlet plugin to make it behave like Spring. I've added this to the current release and I will update the tutorial docs.
