### ISSUE TITLE
"Finer Grain of Control" section of tutorial misses need to set property.

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/stormpath-sdk-java#322]
The [Finer Grain of Control](http://docs.stormpath.com/java/spring-boot-web/tutorial.html#a-finer-grain-of-control) section of the tutorial doesn't make clear that you must set:

    stormpath.spring.security.fullyAuthenticated.enabled = false

The previous section implies (to me) that this property only needs to be set to false if you don't want to take fined grained control of things.

However if you don't set it to false then the `me` "rule" in one's `doConfigure(...)` logic will never be used:

    .antMatchers("/me").fullyAuthenticated()
    .antMatchers("/**").permitAll();

The ordering here (taken from the tutorial) makes you think that  the `/me` rule would be matched against before hitting the `/**` rule. But this isn't the case.

Things actually get setup like this:

1. You hit `com.stormpath.spring.config.StormpathWebSecurityConfigurer.configure(HttpSecurity)`. This adds in `antMatchers("/**").fullyAuthenticated()`.
2. Then the end-users `doConfigure(...)` logic (like above) is hit. This adds in `antMatchers("/me").fullyAuthenticated()` and `antMatchers("/**").permitAll()`.
3. Finally we hit `org.springframework.security.config.annotation.web.configurers.AbstractConfigAttributeRequestMatcherRegistry.createRequestMap()`. This iterates thru the _array_ of mappings that we're created and builds up a linked hash map.

So (after handling mappping for logon etc.) it hits the original `/**` to fully-authenticated mapping, then it hits the `/me` mapping and then it hits the `/**` to permit-all mapping. As the hash map is keyed off the URL patterns, i.e. `/**`, `/me` etc. the permit-all mapping for `/**` replaces the older fully-authenticated mapping but the old ordering is preserved, i.e. `/**` will still be before `/me` in the linked hash map but will now point to permit-all.

So when a request comes in from a browser its URL gets matched against the patterns in this linked hash map in `org.springframework.security.web.access.intercept.DefaultFilterInvocationSecurityMetadataSource.getAttributes(...)` and it will always match against the `/**` pattern (which now point to permit-all) and stop there, never going on and matching against the `/me` mapping or anything else setup by the end user in `doConfigure(...)`.

**Comment by dogeared** [comment]
Thanks for this @george-hawkins-aa. The `1.0.RC5.1` release is going to include code changes as well as changes to the tutorial that will alleviate the need to go into the `stormpath.spring.security.fullyAuthenticated.enabled` property at all.

It's really an advanced topic and, ideally, left out of the tutorial - code and docs.
