### ISSUE TITLE
Stormpath groups fail in multiple places as roles but work fine as authorities

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/stormpath-sdk-java#325]
An expected prefix is set for all role names - by default this is set to `ROLE_`, see:

    org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.rolePrefix

Stormpath role names are always of the form `https://api.stormpath.com/v1/groups/...` so if you call:

    HttpServletRequest request = ...
    request.isUserInRole("https://api.stormpath.com/v1/groups/...") 

You'll eventually hit:

    org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestWrapper.isGranted(String)`.

This will tack the role prefix onto whatever you passed into `isUserInRole(...)` and it ends up trying to match `ROLE_https://...` against the Stormpath roles assigned to the user.

You can fix this in your `StormpathWebSecurityConfigurerAdapter` subclass by setting the prefix to the empty string (null isn't allowed):

    http.servletApi().rolePrefix("");

**Question:** should Stormpath be handling this for you in its setup logic rather than requiring anyone who wants to use `isUserInRole(...)` to set this up?

Note: if you Google setting role prefix to the empty string you see various people advising that this is a "bad idea" - but in the Stormpath context maybe the reasoning behind this doesn't apply.

It might actually be nice to set the role prefix to `https://api.stormpath.com/v1/groups/` then you'd just have to use the last component of a group's path when specifying a group - but I guess that would have knock on consequences in other situations like using e.g. `@PreAuthorize("hasRole(@roles.USER)")` etc.

**Comment by george-hawkins-aa** [comment]
This also affects being able to do e.g.:

    http.authorizeRequests()
        .antMatchers("/foo").hasRole(roles.USER)
        .antMatchers("/bar").access("hasRole(@roles.USER)")

And unlike `HttpServletRequest.isUserInRole(...)` this can't be fixed easily via `http.servletApi()` as the `ROLE_` prefix involved here is completely separate (of course) and controlled separately.

We somehow need to get at the expression handler bean returned by `org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.webSecurityExpressionHandler()`.

This is an instance of `org.springframework.security.web.access.expression.DefaultWebSecurityExpressionHandler`.

Once we'd got that we could call `DefaultWebSecurityExpressionHandler.setDefaultRolePrefix(String)` and fix things in the same fashion as the case above.

But I haven't yet spotted a convenient point to do all this :disappointed:

**Comment by mrioan** [comment]
Hello @george-hawkins-aa. Did you really stumbled into a problem with "ROLE_" prefix in our libraries? We have this solved out by [AbstractStormpathMethodSecurityConfiguration](https://github.com/stormpath/stormpath-sdk-java/blob/master/extensions/spring/stormpath-spring-security/src/main/java/com/stormpath/spring/config/AbstractStormpathMethodSecurityConfiguration.java).

In our examples this is working ok for us, meaning that the "ROLE_" prefix is properly being left aside for us.

Maybe you found out an issue that we haven't yet. If that is the case, could you please share with us an example so we can troubleshoot it?

Thanks!

**Comment by george-hawkins-aa** [comment]
Hi @mrioan - sorry for not getting back quicker, was away for a few days.

Amazingly the Spring people seem to have coded up the check for `ROLE_` separately in at least three different places :disappointed: 

So the solution you mention - `AbstractStormpathMethodSecurityConfiguration` - just covers the check used when using the `@PreAuthorize` annotation.

End-users can also check for role membership using `HttpServletRequest.isUserInRole(...)` and `AuthorizedUrl.hasRole(String)`. Bizarrely both of these use their own separately configurable role prefixes.

I've created a super-mini project that demonstrates all the cases I've found and where to place your breakpoints to demonstrate the issues. See:

https://github.com/george-hawkins-aa/stormpath-roles

It's got a big long [README](https://github.com/george-hawkins-aa/stormpath-roles/blob/master/README.md) with all the details to go with it. Really this should be fixed at the Spring end of things but I don't know how much luck you'd have with that :disappointed:

**Comment by george-hawkins-aa** [comment]
@mrioan - as noted I've found two further independent implementations of the `ROLE_` prefix check that would need to be fixed to get Stormpath groups to be treated as roles.

I've put [a project](https://github.com/george-hawkins-aa/stormpath-spring-boot-example) up on Github where it's easy to demonstrate the issue. When you log in you're presented with buttons that allow you to test four different ways of restricting access:

![restrictions](https://cloud.githubusercontent.com/assets/12233059/11369663/685d8ebc-92c0-11e5-8423-556ce41e92c7.png)

If you try the panel where the restrictions are based around roles you'll see that all but the button using `@PreAuthorize` (as covered in the Stormpath Spring Boot tutorial) fail. The reasons for the failures are explained in the README for my project - see the [authorities vs roles section](https://github.com/george-hawkins-aa/stormpath-spring-boot-example#authorities-vs-roles).

In the above screen shot you can see the buttons repeated but instead of basing the restrictions around roles they're done near identically using authorities - all these restrictions work without any changes being required to the standard Spring logic.

So I suggest forgetting about roles - and treating Stormpath groups as authorities.

Also in the screenshot you'll see two `sec:authorize` Thymeleaf checks - again the role based one fails while the authorities based one works fine.

**Comment by rocketraman** [comment]
> This also affects being able to do e.g.:
> antMatchers("/bar").access("hasRole(@roles.USER)")

Having this issue too. My workaround was to create a Spring Security `ObjectPostProcessor` to set the default role prefix to null:

```kotlin
  override fun configure(http: HttpSecurity) {
    http.apply(stormpath()).and()
      ...
      .antMatchers("/bar/**").access("hasRole(@roles.ADMIN)")
      ...
      .withObjectPostProcessor(webSecurityPostProcessor())
  }

  private fun webSecurityPostProcessor() = object : ObjectPostProcessor<DefaultWebSecurityExpressionHandler> {
    override fun <O : DefaultWebSecurityExpressionHandler> postProcess(o: O): O {
      o.setDefaultRolePrefix(null)
      return o
    }
  }
```

At least for this particular case out of all the cases identified, presumably the apply(stormpath()) should be able to add this post processor.

**Comment by dogeared** [comment]
@george-hawkins-aa @rocketraman - This is an important issue and one that seems fairly easy to address.

I'm adding this to our 1.0 milestone. We'll need to discuss as a team internally the approach we want to take and the impact it could have on existing users, but the examples give us a *huge* leg up on the issue.

Thanks!

**Comment by rocketraman** [comment]
> My workaround was to create a Spring Security ObjectPostProcessor to set the default role prefix to null

I realized this workaround isn't necessary. Based on the OP's statement of "groups fail in multiple places but work fine as authorities", one can simply use `hasAuthority` rather than `hasRole` e.g.:

```antMatchers("/bar").access("hasAuthority(@roles.USER)")```

**Comment by mrioan** [comment]
Javadoc for `ExpressionUrlAuthorizationConfigurer.AuthorizedUrl#hasRole(String)` says:

```
/**
 * Shortcut for specifying URLs require a particular role. If you do not want to
 * have "ROLE_" automatically inserted see {@link #hasAuthority(String)}.
 *
 * @param role the role to require (i.e. USER, ADMIN, etc). Note, it should not
* start with "ROLE_" as this is automatically inserted.
* @return the {@link ExpressionUrlAuthorizationConfigurer} for further
* customization
*/
```

Therefore, what @rocketraman describes is true. When an endpoint is to be secured for `Roles` in `SpringSecurityWebAppConfig#configure(HttpSecurity)` then this is the proper way of doing so:

``
antMatchers("/secured").access("hasAuthority(@roles.USER)")
```

**Comment by dogeared** [comment]
@mrioan - let's add examples of the `hasAuthority` construct in the spring-security and spring-boot-spring-security examples.

It's very powerful to see it used in a thymeleaf template:

```
<a sec:authorize="${hasAuthority(@roles.USER)}" href="...">my link</a>
```

**Comment by george-hawkins-aa** [comment]
Just a reminder - the ["Authorities vs Roles"](https://github.com/george-hawkins-aa/stormpath-spring-boot-example#authorities-vs-roles) section in the README for my demo project (that's referenced [way back](https://github.com/stormpath/stormpath-sdk-java/issues/325#issuecomment-159287440) in this issues's thread) did cover that you can use Stormpath groups as authorities in any situation in Spring without any extra magic. And it does specifically cover the template case, i.e.:
```HTML
<p sec:authorize="${hasAuthority(@roles.FULL_MEMBER)}">...</p>
```
In addition it also covers four other ways you can use roles:
```
// 1. ExpressionUrlAuthorizationConfigurer.AuthorizedUrl.hasRole(String)
...antMatchers("/path/hasRole").hasRole(roles.FULL_MEMBER)

// 2. Spring EL with ExpressionUrlAuthorizationConfigurer.AuthorizedUrl.hasRole(String)
...antMatchers("/path/roleExpression").access("hasRole(@roles.FULL_MEMBER)")

// 3. Spring EL with @PreAuthorize annotiation.
@PreAuthorize("hasRole(@roles.FULL_MEMBER)")
public void roleRestrictedAction() ...

// 4. HttpServletRequest check.
if (!request.isUserInRole(roles.FULL_MEMBER)) ...
```
At the time I wrote this only the `@PreAuthorize` approach (covered in the Stormpath tutorial), worked - maybe things have changed since? But the same logic using the equivalent Spring authority calls etc. (see the README link above) and treating Stormpath groups as authorities rather than roles works without any additional setup being required (either in the Stormpath Java library or in the user configuration logic).

So why not change the documentation to refer to Spring authorities and just forget about roles? And at the same time rename the `Roles` class that users have to create to either `Authorities` (the appropriate Spring term) or `Groups` (the appropriate Stormpath term). I'm actually inclined towards `Groups`.
