### ISSUE TITLE
Make the login views for servlet and spring suppress "Create Account" if there's no default Account Store

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#333]
ID Site does this already:

```
<span ng-show="canRegister" wd-can-register>
    <span> or </span>
    <a href="#register">Create an Account</a>
 </span>
```

`canRegister` is set to false if ID Site is unable to read a default password policy (indicating that there's no default account store).

**Comment by dogeared** [comment]
per the spec: https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md, we should be responding to this property regarding registration: `stormpath.web.register.enabled`

**Comment by dogeared** [comment]
@lhazlewood - is this something you were already working on?

**Comment by lhazlewood** [comment]
@dogeared yep!  It is in the 708-view-enhancements branch, but I only modified the thymeleaf templates.  We can open a PR once we do the same to the JSPs.

**Comment by lhazlewood** [comment]
(p.s. I modified the `LoginController` as well since I needed to represent the state that the templates reacted to.  Only JSP modifications remain to the best of my knowledge).

**Comment by mraible** [comment]
Fixed by https://github.com/stormpath/stormpath-sdk-java/pull/764.

**Comment by lhazlewood** [comment]
Need to re-open as the previously linked PR only addressed turning off the create account link due to properties config, not based on default account store state.

**Comment by lhazlewood** [comment]
@dogeared - I thought of something after I'd (mostly) completed this work:

What if there is no default account store, but the user is allowed to register with a social directory (Google, Facebook whatever) because those are mapped to the application?

The `/register` route should still be allowed, no?

**Comment by lhazlewood** [comment]
Ah, I see - you don't need to visit `/register` when using a 3rd party provider because just the act of logging in lazily creates an account automagically.  Nice.
