### ISSUE TITLE
Tutorial describes steps using gradle but the root of our SDK lacks a build.gradle file

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#334]
Therefore, users wanting to use grandle will also need to use maven to build the project before they can play around with the source code of our tutorial.

Solution: make sure our SDK can be built using gradle.

**Comment by dogeared** [comment]
@mrioan - The tutorials are now standalone and the gradle files work with them. However, there is no way to use the maven deploy plugin to update the version in the gradle build files.

Therefore, I think we should remove gradle files and update the tutorials to speak to generating the build.gradle files from the pom.xml files, which is a standard feature of gradle.

I'll add this in to the 1.0.RC9 milestone as it's a bit of a bug right now.
