### ISSUE TITLE
Support new token management in Servlet Plugin

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#338]
This way, Servlet plugin will provide refresh token capabilities which is currently not supported.

**Comment by mrioan** [comment]
Depends on #232

**Comment by maranai** [comment]
PR for review:
https://github.com/stormpath/stormpath-sdk-java/pull/374

Note: this PR also contains a fix for #262 [Servlet] JWT `ttl` is overflowing

**Comment by dogeared** [comment]
Updated PR for review: #382

**Comment by mrioan** [comment]
Relates to https://github.com/stormpath/stormpath-sdk-java/issues/350
