### ISSUE TITLE
mvn clean package fails

### ISSUE THREAD

**Issue by richierich112582** [stormpath/stormpath-sdk-java#347]
[ERROR] Failed to execute goal on project stormpath-sdk-tutorials-spring-boot-default-the-basics: Could not resolve dependencies for project com.stormpath.sdk:stormpath-sdk-tutorials-spring-boot-default-the-basics:jar:1.0.RC5.2-SNAPSHOT: Failure to find com.stormpath.spring:stormpath-default-spring-boot-starter:jar:1.0.RC5.2-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

**Comment by dogeared** [comment]
@richierich112582 Thanks for reporting this and humble apologies for how long its taken to respond! We've updated our process for replying to issues created by the community and we expect to respond within 48 hours going forward.

I am going to close this issue as we are now on version `1.0.RC8.5`. Please open a new issue if you still encounter any difficulty building the project.
