### ISSUE TITLE
Support options on single object retrieval.

### ISSUE THREAD

**Issue by hereen** [stormpath/stormpath-sdk-java#35]
The documentation(1) currently describes a way to retrieve customData using Link expansion:
```
AccountList accounts = application.getAccounts(
            Accounts.where(Accounts.email().eqIgnoreCase("some@email.com"))
                    .withCustomData()
); 
```
Which requires the user to handle a list even when using a unique value (like email) to return only 1 object. 

A circuitous solution would be to modify the url used in retrieval:
```
Account account = client.getResource("https://api.stormpath.com/v1/accounts/{acctId}*?expand=customData*", Account.class);
```
But this is not very "SDK-like".

Please provide official SDK retrieval support for a single object with expansion options.

--------- End Notes ---------------
(1) http://docs.stormpath.com/java/product-guide/#retrieve-custom-data

**Comment by mrioan** [comment]
Released
