### ISSUE TITLE
Update stormpath spring security antMatcher to include query params

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#362]
Our `/login` (and possibly others) can take a query parameter to trigger showing a status message. This looks like: `/login?status=error`, for instance.

The current `antMatcher` only matches `/login`:

```
.antMatchers("/login")
```

This can cause a redirect loop as `/login?status=error` ends up redirecting to `/login`

**Comment by lhazlewood** [comment]
:+1:
