### ISSUE TITLE
Javascript / Angular Rich Client SPA Support

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#364]
Ensure Servlet/Spring/Spring Boot/Spring Security endpoints are rich-client-compatible per framework spec [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/single-page-apps.md):

* html5 push state mode that will always render a static html file on GETs
* POSTs need to support both form-url-encoded content (server-rendered forms) and JSON (ria/spa)
* 3rd party login providers should display if in the Application's account store mappings

Note: This issue depends on implementing the `application/json` model responses for `/login` and `/register` in [this](https://github.com/stormpath/stormpath-sdk-java/issues/577) issue and [this](https://github.com/stormpath/stormpath-sdk-java/issues/583) issue, respectively.

**Comment by dogeared** [comment]
*Note*: After the `364-spa-support` branch is merged to master, we need to merge `reviewed-blocked_on_364` to master.  `reviewed-blocked_on_364` has a number of PRs merged into it that are dependent on `364-spa-support`.
