### ISSUE TITLE
SAML support in Java

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#371]
### Branches involved in this issue:

- 371_SAML_Support (will be PR'd against master)
- servlet_saml (PR'd against 371_SAML_Support: #434)

### Completion Checklist:
-------------------------------------------------------------------

- [x] SDK
- [ ] javadocs
- [ ] update all new code to have @since 1.0.RC8

|      | Servlet | Spring<br/>WebMVC | Spring Boot<br/>WebMVC | Spring<br/>Security |
|---------------|:--------------------:|:--------------------:|:--------------------:|:--------------------:|
|  /login | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| redirect /login to nextUri<br/>if already logged in | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| /logout | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| /register | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| /forgot | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| /change | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
|  ID Site: /login | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| ID Site: redirect /login to nextUri<br/>if already logged in | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| ID Site: /logout | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| ID Site: /register | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| ID Site: /forgot | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| ID Site: /change | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| Organization Support | <ul><li>- [ ] </li></ul> | <ul><li>- [x] </li></ul> | <ul><li>- [x] </li></ul> |<ul><li>- [x] </li></ul> |
| ID Site: Organization Support | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> | <ul><li>- [ ] </li></ul> |<ul><li>- [ ] </li></ul> |

**Comment by maranai** [comment]
Branch for this work is: 371_SAML_Support  (https://github.com/stormpath/stormpath-sdk-java/issues/371)
