### ISSUE TITLE
Login failure reason not reported when using Spring Security

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/stormpath-sdk-java#378]
If using Spring Boot and the user enters an invalid username or password then no error is reported they just end up back on the login page (the only clue being `?error` at the end of the URL).

The reason for this is that the classic `LoginController` expects to be able to add in the attribute `"errors"` when things fail but when Spring Security is wired into the mix the `UsernamePasswordAuthenticationFilter` actually gets in there first and on failure the user gets redirected to `/login?error` before this logic can be hit:

```
Daemon Thread [http-nio-8080-exec-7] (Suspended)	
	Response.sendRedirect(String) line: 1270	
	ResponseFacade.sendRedirect(String) line: 500	
	FirewalledResponse(HttpServletResponseWrapper).sendRedirect(String) line: 138	
	FirewalledResponse.sendRedirect(String) line: 26	
	HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper(HttpServletResponseWrapper).sendRedirect(String) line: 138	
	HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper(OnCommittedResponseWrapper).sendRedirect(String) line: 115	
	DefaultRedirectStrategy.sendRedirect(HttpServletRequest, HttpServletResponse, String) line: 42	
	SimpleUrlAuthenticationFailureHandler.onAuthenticationFailure(HttpServletRequest, HttpServletResponse, AuthenticationException) line: 76	
	UsernamePasswordAuthenticationFilter(AbstractAuthenticationProcessingFilter).unsuccessfulAuthentication(HttpServletRequest, HttpServletResponse, AuthenticationException) line: 357	
	UsernamePasswordAuthenticationFilter(AbstractAuthenticationProcessingFilter).doFilter(ServletRequest, ServletResponse, FilterChain) line: 235	
    ...
```

As you can see this all happens in the filters - things never get to the underlying `LoginController`.

If we look in [`login.html:39`](https://github.com/stormpath/stormpath-sdk-java/blob/ce0d5b2a2603961dddc1018685eaa38dac5fdf80/extensions/spring/boot/stormpath-thymeleaf-spring-boot-starter/src/main/resources/templates/stormpath/login.html#L39) we see:

```html
<div class="alert alert-dismissable alert-danger bad-login" th:if="${errors != null and not #lists.isEmpty(errors)}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <!--/*/ <th-block data-th-each="error : ${errors}"> /*/-->
    <p th:text="${error}">|Error message here.|</p>
    <!--/*/ </th-block> /*/-->
</div>
```

I.e. it's expecting an `errors` list to be filled in.

We can see some of the logic to do this in [`LoginController.toErrors(...)`](https://github.com/stormpath/stormpath-sdk-java/blob/a6c61cf8cd2def96855da5c0d4b099b4e00ecfe5/extensions/servlet/src/main/java/com/stormpath/sdk/servlet/mvc/LoginController.java#L160):
```java
log.debug("Unable to login user.", e);
List<String> errors = new ArrayList<String>(1);
errors.add("Invalid username or password.");
return errors;
```

If we look at the call hierarchy for `LoginController.toErrors(...)` we see the problem - it's called via the `doPost(...)` method:

```
com.stormpath.sdk.servlet.mvc.LoginController.toErrors(HttpServletRequest, Form, Exception)
  com.stormpath.sdk.servlet.mvc.FormController.onErrorSubmit(HttpServletRequest, HttpServletResponse, Form, Exception)
    com.stormpath.sdk.servlet.mvc.FormController.doPost(HttpServletRequest, HttpServletResponse)
```

We never hit `doPost(...)` - the `UsernamePasswordAuthenticationFilter` has already intervened, determined that the username or password were incorrect and redirected us to the login page again, but as a `GET` request.

If we look at the `toErrors(...)` logic above we can see it's pretty simple minded - it assumes the only source of error can be an invalid username and password. So a simple solution is to change the part of the `login.html` template shown above to:
```html
<div class="alert alert-dismissable alert-danger bad-login" th:if="${param.error != null}">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <!-- The real error is included as a tooltip, i.e. the title attribute. -->
    <p th:title="${session.SPRING_SECURITY_LAST_EXCEPTION.message}">Invalid username or password.</p>
</div>
```
I.e. we check for `error` in the URL and like the existing simple minded logic just display "Invalid username or password." to the user - but we include the real reason (which Spring helpfully stored away for us in the session) as a tooltip. You can see this in action here - and see that in this case the underlying reason is more complex than an invalid password:
![disabled account](https://cloud.githubusercontent.com/assets/12233059/11571487/ef7f6bb6-99fc-11e5-87b7-eaca8482a30c.png)

You can see this fix checked into my Stormpath demo project as commit [`e664d8e`](https://github.com/george-hawkins-aa/stormpath-spring-boot-example/commit/e664d8ef5e6f43ac20b97f687f65fb6d3f7a944b).

Of course this would break things for people who just want the classic servlet setup without any of the Spring extras :disappointed: One could make the template logic more complex - i.e. look out for the old `"errors"` attribute and the new Spring related stuff - or one could make some changes in the underlying code to fill out `"errors"` in the Spring situation as well.

**Comment by dogeared** [comment]
Hi @george-hawkins-aa -

I release 1.0.RC7 today, which among other things, fixes this issue.

Bad username and password error message now shows both in the servlet JSP templates and the Thymeleaf templates used with Spring.

Please confirm when you have a chance!

-Micah

**Comment by george-hawkins-aa** [comment]
Cool - updated to 1.0.RC7.1 and can confirm this change :smile: 

Any exception on the server side no matter what, including a disabled account, gets reported as "invalid username and password" but I guess that's fair enough, exposing too much data to the user can be just confusing (and revealing arbitrary login related exceptions to the user presumably presents a risk - people get to see possibly "interesting" failures deep in the system).

**Comment by dogeared** [comment]
Sweet! Perhaps an enhancement would be:

Unable to login. Please check your username and password.

This is a little more descriptive without giving away any sensitive information.

**Comment by george-hawkins-aa** [comment]
The simpler the expression the better I think when dealing with end users!

A more complex formulation may be technically more correct but I think it's fine as it is.

I see Gmail for example just seems to say "The email and password you entered don't match." no matter what you do, so this kind of thing seems to be pretty standard.

I see you're working late into Sundays now - hope the 1.0 release doesn't kill you all! Good luck :smile:

**Comment by lhazlewood** [comment]
@george-hawkins-aa Thanks again for your awesome information!  We *LOVE* this stuff - please keep it coming whenever you find anything. :)

That said, you might have noticed a new `com.stormpath.sdk.servlet.mvc.ErrorModelFactory` interface.  This was created to support both Spring and non Spring environments.  In an effort to get 1.0.RC7.1 out quickly for a customer, we chose the simpler solution where if there is any error in the URI, we show the generic error message:

Here's the new `SpringSecurityLoginErrorModelFactory`:

https://github.com/stormpath/stormpath-sdk-java/blob/867fdf805aedf9606ecdb6e12460f5614a165e4b/extensions/spring/stormpath-spring-security-webmvc/src/main/java/com/stormpath/spring/config/SpringSecurityLoginErrorModelFactory.java#L20

A more sophisticated approach would check the HttpSession for Spring Security's AuthenticationException and perhaps show a different error message, and we'd be happy to add that should people want specific error messages - we just took the safe approach to not give the end-user reasons for failure per usual security best practices.  (The current approach also does not require HttpSessions, which many of our customers do not want due to wanting 100% stateless backends for Angular apps).

HTH!

**Comment by lhazlewood** [comment]
P.S. It is also weird that we're not using i18n for this - we use it everywhere else in page templates.  This should be i18nified as well.  cc @dogeared

**Comment by dogeared** [comment]
Thanks @george-hawkins-aa @lhazlewood.

I will create a new issue to i18nify the message and I will close this issue.
