### ISSUE TITLE
Session saver throws Exception after login 

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#397]
In our servlet Plugin we get a
`IllegalArgumentException: An authenticated account must be represented with a specific request authType` when `session` is used rather than `cookie` (`stormpath.web.authc.savers = session`)

**Comment by mrioan** [comment]
In order for this fix to work, the following configuration is required:

stormpath.web.authc.savers = session
stormpath.web.account.resolvers = session

**Comment by lhazlewood** [comment]
@mrioan is this a bug?  Or just a misconfiguration?

If the only thing you needed to change was the two specified properties, it sounds like misconfiguration to me and not a bug.  Thoughts?

**Comment by mrioan** [comment]
@lhazlewood It was a bug: missing `request.setProperty` in `SessionAccountResolver.java`

**Comment by mrioan** [comment]
Solved in #402
