### ISSUE TITLE
Servlet Plugin is not Social aware

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#399]
When an Application has Facebook/Google/etc Account Stores the Servlet Plugin's login screen should display the corresponding social login buttons. This is currently not supported.

**Comment by lhazlewood** [comment]
I'm currently working on this in the context of #364 (since it's in the spec that issue references).

**Comment by Olatunji-Longe** [comment]
Thanks @mrioan for opening this issue on my SO request. I'll be actively following up on this. Gracias!

**Comment by dogeared** [comment]
related to #168

**Comment by dogeared** [comment]
This has been merged to master per #673 and will be included in the 1.0 release
