### ISSUE TITLE
Method createAccount on Directory object returns void

### ISSUE THREAD

**Issue by sinaisix** [stormpath/stormpath-sdk-java#400]
![screenshot from 2015-12-11 23 12 51](https://cloud.githubusercontent.com/assets/3254773/11757935/672c0bae-a05d-11e5-98ef-6de3f2d974a6.png)
![screenshot from 2015-12-11 23 13 07](https://cloud.githubusercontent.com/assets/3254773/11757934/663413ae-a05d-11e5-9275-99db46075546.png)

According to the api docs, calling createAccount on a directory returns the newly created account. But I get an error from my IDE telling me the method returns void. Also looking at the decompiled class file shows the createAccount on interface Directory indeed returns void. 

Could it be I've misunderstood something? Thanks

**Comment by lhazlewood** [comment]
Please check that you are using the latest stable Java SDK version.  The current version returns Account instances:

https://docs.stormpath.com/java/apidocs/com/stormpath/sdk/directory/Directory.html#createAccount-com.stormpath.sdk.account.Account-

Can you please let us know what version you're using?

**Comment by sinaisix** [comment]
![screenshot from 2015-12-11 23 40 13](https://cloud.githubusercontent.com/assets/3254773/11758242/a9775088-a060-11e5-8405-f76b60774b9e.png)

I just grabbed those version numbers from maven. Still the same. Thanks

**Comment by lhazlewood** [comment]
I think there might be something broken in your classpath or IDE?  The linked JavaDocs and the [Directory class source code for 1.0.RC7.2](https://github.com/stormpath/stormpath-sdk-java/blob/stormpath-sdk-root-1.0.RC7.2/api/src/main/java/com/stormpath/sdk/directory/Directory.java#L116), the `Directory.getAccount`* methods definitely reflect a returned Account instance.

**Comment by sinaisix** [comment]
Hmmmm. Done a mvn clean and re-imported, still. It's almost 12 am here in Accra Ghana. I'll sleep over this and try to troubleshoot tomorrow. I'll report back here. Thanks a lot for your time sir, very much appreciated.

**Comment by lhazlewood** [comment]
Good luck!  Let us know how it goes.

**Comment by lhazlewood** [comment]
Any update on this?  I'd like to close it out if there is no new information.  Please advise.  Thanks!

**Comment by sinaisix** [comment]
Sorry for the long silence. Still couldn't get it to work. Same issue persisted.

**Comment by lhazlewood** [comment]
I'm afraid without a sample project, we'll have to close this issue - no one on our end can reproduce.

**Comment by dogeared** [comment]
per @lhazlewood, closing
