### ISSUE TITLE
Replacement for deprecated application.authenticateApiRequest and application.authenticateOauthRequest?

### ISSUE THREAD

**Issue by francisdb** [stormpath/stormpath-sdk-java#407]
both `application.authenticateApiRequest` and `application.authenticateOauthRequest` are deprecated

The javadoc mentions something like this
 
    @deprecated in 1.0.RC4.6 and will be removed before 1.0 final. Use {@link com.stormpath.sdk.api.ApiRequestAuthenticator#authenticate(com.stormpath.sdk.http.HttpRequest)} instead.
  
The question is how to get an instance of ApiRequestAuthenticator and OauthRequestAuthenticator?

Also the guide at http://docs.stormpath.com/guides/api-key-management/#how-do-i-use-stormpath-for-api-authentication still mentions these deprecated calls

**Comment by dogeared** [comment]
Hello @francisdb:

Sorry for the late reply, here. Thanks for pointing this out. We will definitely update the docs in the new release. 

This part of the Java SDK is likely to go through a few more changes before the 1.0 release.

A more up-to-date guide is here: https://docs.stormpath.com/guides/token-management/

I understand that having this documentation in two places with one being outdated is confusing. We will definitely rectify this in our upcoming 8.1 release. I've added this issue to that milestone to track it.

Thanks,

Micah

**Comment by mzumbadoate** [comment]
the PR is
https://github.com/stormpath/stormpath.github.io/pull/238
