### ISSUE TITLE
Deprecated UsernamePasswordRequest has no alternative

### ISSUE THREAD

**Issue by maxkremer** [stormpath/stormpath-sdk-java#408]
All the methods in `UsernamePasswordRequest` appear to be deprecated. Why not just deprecate the class. Since this is a public api the docs for deprecated stuff should point the user at the new stuff like so

```
/**
 * Does some thing in old style.
 *
 * @deprecated use {@link #new()} instead.  
 */
@Deprecated
public void old() {
// ...
}
```

**Comment by dogeared** [comment]
@maxkremer:

Thanks for this and sorry for the (very) delayed response. We are working on improving our process and responsiveness on github and going forward, we will reply within a day or two at most.

`UsernamePassrordRequest` now follows the builder pattern that we use in many other places in the SDK.

Per the javadocs [here](https://docs.stormpath.com/java/apidocs/com/stormpath/sdk/authc/UsernamePasswordRequest.html):

```
AuthenticationRequest request = UsernamePasswordRequest.builder()
    .setUsernameOrEmail(username)
    .setPassword(submittedRawPlaintextPassword)
    .build();
```

I *do* see that the javadocs indicate that the class has been deprecated, which is not accurate. It is all the constructors that have been deprecated.

I will leave this issue open and add it to our `1.0.RC9` milestone to update the javadocs.

**Comment by maxkremer** [comment]
ok thanks for the update @dogeared

**Comment by lhazlewood** [comment]
Final comments on this one - we did indeed deprecate the entire `UsernamePasswordRequest` class and added a new `UsernamePasswordRequests` utility class (like `Accounts`, `Applications`, etc) that creates builders as expected.
