### ISSUE TITLE
idpRedirect does not authorize with API Key returns 401

### ISSUE THREAD

**Issue by claytantor** [stormpath/stormpath-sdk-java#418]
Using valid credentials and basic auth (this key is working with other endpoints) the idpRedirect call returns a 401 
https://staging-veritas.stormpath.io/v1/applications/6inFkY8mp7h9kqUNu5Ozqe/saml/sso/idpRedirect

```
{
  "status": 401,
  "code": 401,
  "message": "Authentication required.",
  "developerMessage": "Authentication with a valid API Key is required.",
  "moreInfo": "http://www.stormpath.com/docs/quickstart/connect"
}
```

**Comment by dogeared** [comment]
Hey @claytantor -

Catching up here. Sorry for the delay in response. If this is still an issue, please log a support request at: support@stormpath.com

I am going to close this issue out here. 

We are putting procedures in place to ensure that we will be much more responsive on Github.
