### ISSUE TITLE
Add documentation to spring boot about customizing views and adding additional fields for account registration

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#420]
Feedback from a enterprise customer on a call.

He wants step by step guide to how to add additional fields to the registration form.

**Comment by lhazlewood** [comment]
I believe this issue may depend on #287, which will implement the standard for configuring fields on any of our forms.  The existing way is deprecated.

**Comment by dogeared** [comment]
Adding this to the 1.0 milestone.
