### ISSUE TITLE
Most views should redirect if already logged in

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#421]
All stormpath views *except* 'change password' (note this is change password - not 'forgot password') should redirect an already-logged-in user to the login nextUri.

Allowing users to indicate they forgot their password or register another user while already logged in is unintuitive at best, and might be a security concern at worst.

All GET requests should all be redirected and any POST should return an error.  The reason is that if a GET always redirects, it should never be possible to POST (since you'd never see the original form that the GET would have returned).  If POSTing occurs, then, it is probably someone trying to be sneaky, or something went wrong (e.g. CDN caching a view which shouldn't be cached), both of which should be prevented for safety/security.

**Comment by jarias** [comment]
@lhazlewood what error code should we return for a POST? I was thinking 403 but just want to confirm.

**Comment by lhazlewood** [comment]
Yep, 403 Forbidden
