### ISSUE TITLE
Small modifications to the spring boot quickstart

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#423]
Feedback from Ramesh on the JAVA SDK (Spring Boot Starter) :

> Links (on click) should open the resource in a new tab -> All the links in the documentations, when clicked should Ideally open a new tab on the browser, instead of taking the user away from the documentation in the same tab. Of course, I can just right click on the link and open it in a new tab instead of directly  clicking it, but mostly often than not people tend to directly click on the link, and if that takes the user away from the actual documentation on the same tab, it may cause a lot of inconvenience and we are potentially driving users away from our documentation, and they may never return.

> Get an API Key -> In Point 3 (screenshot below) , shouldn’t there must be a mention of the “Tenant” (in addition to Email and Password)?

> Get an API Key -> In Point 4 (screenshot below), the button is actually in the right side of the page, not in the middle. In either case, the positioning can change again in future, therefore it is not advisable to mention it in the documentation. Just saying "Click the Create API Key or Manage Existing Keys button" should be sufficient. Users should be able find a damn button. :-)

**Comment by jarias** [comment]
The first point bout external links would also apply to the servlet starter guide

**Comment by jarias** [comment]
Actually all 3 points apply to the servlet plugin tutorial too
