### ISSUE TITLE
Internationalization not working

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#427]
Trying to change languages as explained here does not work: http://docs.stormpath.com/java/servlet-plugin/i18n.html

I tried with `spring-security-webmvc` sample.

**Comment by maranai** [comment]
I followed the steps in the guide and internationalization worked fine. The only problem I found is a little lack of clarity about the package directory that needs to be created. If this directory is created on the project's root directory it will not work so I modified the documentation to let the users know where in the project the new directory needs to be created.
This is a pretty small change, PR for review: https://github.com/stormpath/stormpath.github.io/pull/227
