### ISSUE TITLE
decide on functional testing framework for JSDK

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#430]
Cargo? https://codehaus-cargo.github.io/cargo/Home.html

**Comment by dogeared** [comment]
This is now (mostly) handled in the TCK project: https://github.com/stormpath/stormpath-framework-tck. Do we still want to look for something internal to the Java SDK project?

**Comment by lhazlewood** [comment]
My .02: I think the TCK is sufficient - at least until we decide it's not, so we can close this and re-open later if necessary.
