### ISSUE TITLE
Integrate code coverage plugin for unit and integration tests

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#431]
Jacoco? I say: Yes

Cobertura is not actively maintained.

IntelliJ supports using Jacoco as its coverage tool so command line will match IntelliJ

Need to determine baseline: What % coverage satisfies this ticket to start with? That should be enforced in the pom.xml.

**Comment by omgitstom** [comment]
Where are we with the SDK?
Where are we with Servlet?
Where are we with Spring?

**Comment by dogeared** [comment]
branch coverage_jacoco_coveralls is in progress for this issue. PR #457 was closed as it was not yet ready.
