### ISSUE TITLE
Disabled Group still allows access in endpoint protected by Spring Security

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#445]
As reported by @jaschenk:

Using the latest Java SDK 1.0.RC8, I have found the following security issue with Groups. 
Current flow:

* Application Boots (Java Spring Boot) 
* Perform a Login and test Restricted Access. Access correctly ALLOWED per Group.

* Go to Stormpath Admin Console and Disable the Group.

* Attempt a Login and test Restricted Access, Access ALLOWED when a Group was Disabled. This does not seem correct!

* Log out. 
* Go to Stormpath Admin Console Re-enable disabled Group. 
* Go to specific Login Account for Application and Remove Group. 
* Login to App and test Restricted Access, Access Forbidden. 
* Re-Add Group to Account. 
* Login to App and test Restricted Access, Access Correctly ALLOWED.

I verified this behavior configuring the [Spring Boot tutorial](https://github.com/stormpath/stormpath-sdk-java/tree/master/tutorials/spring-boot/03-spring-security-refined) to use a Group. When I disable the Group, users in that Group still have access to the `/restricted` page - even after rebooting the application.

We will need to check and see if this is just a Spring Security issue or if it is a general issue in the JSDK.

**Comment by lhazlewood** [comment]
Back to @jarias based on latest code review (sorry for not catching these earlier!)
