### ISSUE TITLE
Servlet Plugin does not support disabling controllers

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#446]
Spring and Spring Boot do support doing things like this:

stormpath.web.login.enabled = false
stormpath.web.forgot.enabled = false
stormpath.web.register.enabled = false
stormpath.web.verify.enabled = false
stormpath.web.logout.enabled = false
stormpath.web.change.enabled = false
stormpath.web.idSite.enabled = false
stormpath.web.accessToken.enabled = false

The Servlet Plugin does not support these properties.

The change seems to be needed in `DefaultFilterChainResolverFactory#createInstance()`.

**Comment by dogeared** [comment]
This has been addressed in #720
