### ISSUE TITLE
bring all dependencies up to latest version

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#473]
- httpclient
- spring boot - #463 
- hazelcast - #476 
- what else?

**Comment by mzumbadoate** [comment]
will upgrade
Spring Boot from 1.3.2.RELEASE and 1.3.0.RELEASE to 1.3.3.RELEASE
hazelcast  from 3.2.4 to 3.6.1
what else?

**Comment by mzumbadoate** [comment]
httpcomponents - httpClient from 4.2.2 to 4.5.2
spring boot from - 1.3.2.RELEASE and 1.3.0.RELEASE to 1.3.3.RELEASE
hazelcast is already using the latest 3.6.1
what else?
