### ISSUE TITLE
Reset password handling - custom email send 

### ISSUE THREAD

**Issue by tomekl007** [stormpath/stormpath-sdk-java#499]
As a developer, using stormpath API, i don't want to send email with url with sptoken to user automatically by stormpath. I want to be able to handle sending email by myself. Application should have method similar to sendPasswordResetEmail but that method should prepare sptoken without sending actual email. I want to send that email myself.

**Comment by mrioan** [comment]
Hello @tomekl007 . You can do so by disabling the Reset Password workflow in the directory where those accounts belong. In that case, when you do `PasswordResetToken passwordResetToken = application.sendPasswordResetEmail("foo@email.com");` you will still receive the token (`passwordResetToken.getValue()`) but the email will not be sent. 

Please let us know if this works for your so we can close the issue.

Regards!

**Comment by tomekl007** [comment]
Ok, disabling that workflow helped. Thank you
