### ISSUE TITLE
Migrate documentation from Stormpath Spring Security wiki

### ISSUE THREAD

**Issue by rocketraman** [stormpath/stormpath-sdk-java#504]
When going to the repo: https://github.com/stormpath/stormpath-spring-security one gets a message that everything has been migrated into this sdk project.

However, the documentation on the wiki (https://github.com/stormpath/stormpath-spring-security/wiki) re. how to use customData for permissions management with Spring is found nowhere in the SDK docs. Suggest migrating that information, as it is pretty important.

**Comment by dogeared** [comment]
Hey @rocketraman - Thanks for pointing the wiki out. We will integrate this documentation into the broader documentation we have for the Java SDK. I've added this to our 1.0 milestone.
