### ISSUE TITLE
Custom Data Search Documentation

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-java#509]

**Comment by dogeared** [comment]
For now, this should be the querParams approach until we have the fluent interface features.

**Comment by markwoon** [comment]
Wait, so is this possible now, just not documented?

**Comment by lhazlewood** [comment]
It's not yet ready, but we're getting close.  This ticket is specifically to ensure we document it so it can be understood at the time it is announced.  HTH!

**Comment by jarias** [comment]
PR in stormpath-documentation https://github.com/stormpath/stormpath-documentation/pull/279
