### ISSUE TITLE
Update servlet plugin cache documentation to fix tti reference

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#517]
https://docs.stormpath.com/java/servlet-plugin/caching.html

Should be `tti` not `ttl`

![servletcache](https://cloud.githubusercontent.com/assets/364562/13658542/01d5eb88-e646-11e5-9186-06c48952554b.png)

**Comment by lhazlewood** [comment]
Just noting that the code sample shows `ttl` instead of `tti` as well.

**Comment by jarias** [comment]
@lhazlewood Couldn't find in the samples where it was also wrong.

**Comment by lhazlewood** [comment]
The code sample for Default TTL shows `stormpath.cache.ttl` (a trailing L not an i) in the above screenshot.  Are you saying it has been fixed already?
