### ISSUE TITLE
Custom data updates are not reflected on collections

### ISSUE THREAD

**Issue by demboos** [stormpath/stormpath-sdk-java#519]
Hi,

I've got caching related issues with the following scenario on Stormpath java Api v.1.0.RC8.3

1. retrieve an account by href
2. retrieve a specific group from account.getGroups collection
3. modify the group's custom data (add an attribute)
4. save the group

5. retrieve the account again by href
6. retrieve the same group using account.getGroups collection
7. check the custom data - the new attribute is not there 

8. retrieve the group by href, by calling

application.getResource, then check the custom data - new attribute is there

I've found a similar issue #30, but that one is already resolved and not related to collections.

**Comment by dogeared** [comment]
Hey @demboos:

Thanks, again! Please also submit this to `support@stormpath.com`. I've added this issue to our current release.

Best,

**Comment by mrioan** [comment]
Hello @demboos.

I followed the steps you mentioned but everything works ok for me:
```
Account account = client.getResource(accountHref, Account.class); //1
Group group = account.getGroups(Groups.where(Groups.name().containsIgnoreCase(groupName))).single(); //2
group.getCustomData().put("issue519", "testing01"); //3
group.save(); //4

account = client.getResource(accountHref, Account.class); //5
group = account.getGroups(Groups.where(Groups.name().containsIgnoreCase(groupName))).single(); //6
Assert.isTrue(group.getCustomData().get("issue519").equals("testing01")); //7

group = client.getResource(groupHref, Group.class); //8
Assert.isTrue(group.getCustomData().get("issue519").equals("testing01"));
```

Can you check if there is some difference on what I did compared to what you are doing?

**Comment by demboos** [comment]
Hi,

1. I was running the code insinde a Spring Boot setup with Spring cache enabled, and Stormpath client using this cache.

2. I'll try to prepare a testing scenario for which it fails and produces the error I described, or I'll fail in doing that... ;)

Thanks,

Szymon

**Comment by jarias** [comment]
Couldn't reproduce it with Spring Boot either

```java
@SpringBootApplication
@EnableCaching
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}

@Controller
public class TestController {

    @RequestMapping("/test")
    public String test(HttpServletRequest request) {

        Account account = AccountResolver.INSTANCE.getAccount(request);
        if (account != null) {
            name = account.getGivenName();
            String accountHref = account.getHref();
            String groupHref = "https://api.stormpath.com/v1/groups/xxxxx";
            String groupName = "testGroupName";

            Group group = account.getGroups(Groups.where(Groups.name().containsIgnoreCase(groupName))).single(); //2
            group.getCustomData().put("issue519", "testing01"); //3
            group.save(); //4

            account = client.getResource(accountHref, Account.class); //5
            group = account.getGroups(Groups.where(Groups.name().containsIgnoreCase(groupName))).single(); //6
            Assert.isTrue(group.getCustomData().get("issue519").equals("testing01")); //7

            group = client.getResource(groupHref, Group.class); //8
            Assert.isTrue(group.getCustomData().get("issue519").equals("testing01"));

            return "Ok";
        }

        return "Fail"
    }
}
```
