### ISSUE TITLE
Update examples poms to inherit from the examples root pom

### ISSUE THREAD

**Issue by jarias** [stormpath/stormpath-sdk-java#522]
Currently only the servlet example is configured this way due to ticket #500 and the discussions around it.

We might also want to create a README file at the examples level to include some instructions if needed to run examples in general.

**Comment by dogeared** [comment]
@jarias - we had originally removed the parent dependency on all the examples and tutorials so that they could be used standalone. If we re-introduce the parent dependency, will we still be able to grab a jar and run it in the case of spring boot or deploy it in the case of servlet or spring?

**Comment by jarias** [comment]
@dogeared I think so

**Comment by dogeared** [comment]
Resolved by #725
