### ISSUE TITLE
Update build.gradle files in examples and tutorials during deploy

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#526]
The Maven release plugin automatically updates all the versions in the `pom.xml` files of the modules.

We need something similar for the `build.gradle` files.

**Comment by jarias** [comment]
After talking to @mrioan he mention that we can generate build.gradle files out of a pom.xml which could fix this issue by updating the documentation telling users if you want to use gradle just run inside the tutorial step they want to run:

```
gradle init --type pom
```

There is only one caveat everything translate pretty good except the `spring-boot` plugin, users would have to manually add the following snippet:

```groovy
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.3.0.RELEASE")
    }
}

apply plugin: 'spring-boot'
```
This way we don't need maintain the gradle stuff at all.

@dogeared @lhazlewood @omgitstom What do you guys think about this, to me its a reasonable solution from a user perspective.

**Comment by jarias** [comment]
Going to mark this as blocked, till I get some feedback

**Comment by lhazlewood** [comment]
This is lower prio IMO - I feel that we need to focus on implementing features before we optimize for examples (because those examples can always come in a later point release).  But if you guys feel otherwise, that's cool - let's discuss.

**Comment by jarias** [comment]
@lhazlewood makes sense I wonder if there is a way to move to the bottom of the column so it has lower prio. @dogeared what do you think?

For now I'll move it back to the ready column.

**Comment by jarias** [comment]
Looks like I can just drag it to the bottom of the ready column and it will stay there.

**Comment by mraible** [comment]
We have a similar problem on the [JHipster](https://github.com/jhipster/generator-jhipster) project. Because we support both Maven and Gradle as build tools, they often get out of sync when we update dependencies. We still have a manual process for updating. As long as the updater is concious of Gradle, it's usually not an issue. We don't auto-update the Maven dependencies as everything is in a template. For example: [_pom.xml](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_pom.xml) and [_gradle.properties](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/_gradle.properties).

**Comment by dogeared** [comment]
For 1.0: we will (1) remove all the build.gradle files from the project and (2) update the relevant docs to instruct people to build it using the `gradle init --type pom`

**Comment by dogeared** [comment]
gradle files have already been moved. Docs still need to be updated. Moving this to the backlog for now.

**Comment by mraible** [comment]
@dogeared I'm not sure we should document how to use Gradle. If it was as easy as `gradle init --type pom`, then possibly. However, it doesn't work. I tried running that command on examples/spring-webmvc and here's the problems it produces:

1. When running `gradle test`, the following happens. To fix this, you have to add `apply plugin: 'war'` at the top of `build.gradle`.

    ```
    FAILURE: Build failed with an exception.

    * Where:
    Build file '/Users/mraible/dev/stormpath-sdk-java/examples/spring-webmvc/build.gradle' line: 34

    * What went wrong:
    A problem occurred evaluating root project 'stormpath-sdk-examples-spring-webmvc'.
    > Could not find method providedCompile() for arguments [{group=javax.servlet, name=javax.servlet-api, version=3.1.0}] 
    on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
   ```

2. There's no way to run the example with the Gradle file produced. Sure you could run `gradle war` and deploy it on your own, but the [Gradle Tomcat Plugin](https://github.com/bmuschko/gradle-tomcat-plugin) seems like a better solution. 

If you'd still like to have Gradle support documented, I can work on trying to get the Tomcat plugin working.

**Comment by mraible** [comment]
Closed because we don't have Gradle files anymore and they're not easily generated.
