### ISSUE TITLE
SpringSecurityResolvedAccountFilter performs a costly authentication on every request

### ISSUE THREAD

**Issue by demboos** [stormpath/stormpath-sdk-java#529]
While the purpose of SpringSecurityResolvedAccountFilter is clear to me, I have a feeling it should not produce a new Authentication every time it runs. Each authentication means reading the Groups the user is member of, and this is very costly as collections are not (yet) cached.

I think the SpringSecurityResolvedAccountFilter should check if the current Authentication (the user href inside the UserDetails) matches the account resolved from request (probably from cookie param). Only if the authentication in the context does not match, or does not exist, a new authentication should be performed.

I've modified the filter to meet those needs and it works quite good, eliminating the communication to Stormpath on every possible request. The performance gains are very noticable, esp. where there are a lot of resources to load (css, js, images).

**Comment by dogeared** [comment]
Hi @demboos. Thanks for the feedback. We will investigate this and prioritize against our 1.0 release. Would you be willing to post your modification as a PR to the project?

**Comment by demboos** [comment]
No problem. This code definitely needs some serious thinking about proper refresh conditions.

```
protected void filter(HttpServletRequest request, HttpServletResponse response, FilterChain chain)
            throws Exception {

        Account account = AccountResolver.INSTANCE.getAccount(request);

        if (account != null) {
            Authentication currentAuthentication = SecurityContextHolder.getContext().getAuthentication();

            boolean forceRefresh = false;

            if (currentAuthentication == null || !SecurityContextHolder.getContext().getAuthentication().getPrincipal() instanceof StormpathUserDetails) {
                forceRefresh = true;
            } else {
                StormpathUserDetails userDetails = (StormpathUserDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
                forceRefresh = Optional.ofNullable(userDetails.getProperties().get("href"))
                        .map(t->!account.getHref().equals(t))
                        .orElse(Boolean.TRUE);
            }

            if (forceRefresh) {
                Authentication authentication = new ProviderAuthenticationToken(account);
                authentication = authenticationProvider.authenticate(authentication);
                SecurityContextHolder.clearContext();
                SecurityContextHolder.getContext().setAuthentication(authentication);
            }

        }

        chain.doFilter(request, response);
    }
```
