### ISSUE TITLE
Collections are never cached resulting in high amounts of API calls

### ISSUE THREAD

**Issue by BToersche** [stormpath/stormpath-sdk-java#532]
The WriteCacheFilter never caches complete collections. It will cache each item within that collection however. This results in doing unnecessary calls to Stormpath for obtaining Groups of an Account for instance.
Since accounts and their groups tend to be required for authorization, this results in doing a Stormpath call for fetching the GroupList of an Account for every call towards an app using Stormpath (even though the Account and its Groups themselves are fetched from cache). 

There seems to be a feature implemented within the SDK allowing enabling of collection caching. However, this seems to be an experimental feature and not yet production ready.

**Comment by mrioan** [comment]
@BToersche The rationale behind not having collection caching is that any modification of any resource within a collection causes the entire collection to be invalidated, and a new version reflecting the latest quantity and order needs to be acquired.

For example, if I have a collection containing application accounts sorted by username, and someone changes their username, the cached version of that collection is now invalid: a new one needs to be obtained that reflects the new username in the correct position in the collection.

While auto-invalidating collections can be done via the SDK (i.e. if you change an account and call `account.save()`, then you invalidate the application.getAccounts()), you also have to invalidate any group or directory collection that contains the account. This means you need to know, up front, what all of those collections are (this is doable, but complicated and not very efficient). Any time an application is added to a group or to a directory or to an application, or any time an account store is assigned to or removed from an application, all of these collections all need to be tracked.

To make matters worse, if these collections are updated at even remotely regular intervals (i.e. add an account to an application from a signup and this happens once every few minutes), it effectively makes collection caching for that collection useless - if any collection changes with regular frequency, the new collection must be obtained, which requires bypassing the cache.

In summary, collection caching is useless if the collection state changes frequently, either by the application using the SDK or out-of-band (e.g. an admin using the user interface to make changes). This is a common problem encountered by almost all ORMs (Hibernate, Rails, etc) and they all pretty much require the app developer to jump in and configure exactly which collections are cached and for how long.

Having said all that we do plan to support collection caching in the future, I cannot give an ETA but it will not be soon.

The best thing you can do for now is to implement collection caching right in your App.

We will keep this issue open so we can work on this in the future.

**Comment by hflink** [comment]
I would also like to see some sort of support for collection caching. It may have it's drawbacks when data changes, but in the end, it's organizational data we are talking about right? It will not change that frequently, at least not for us or our customers. So a collection cache invalidation occurring now and then is still better than having to do an API call for every list, or do the caching ourselves.
