### ISSUE TITLE
Spring MVC: Use filter-based content rendering instead of terminal controllers

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#542]
As discussed in https://github.com/stormpath/stormpath-framework-spec/issues/62#issuecomment-201006919 :

It would be better for the end-user to render their SPA view by letting the request 'fall through' to a user-defined controller if a request should not be processed by the Stormpath integration.  Our Servlet plugin already follows this approach; this issue represents the work for our Spring MVC support to follow the same approach.

Our spring mvc support currently renders requests by registering controllers in Spring directly rather than letting a filter determine if the request should be rendered.  The change then is to not register controllers but to register filters that delegate to a controller if they are enabled (as our Servlet integration already does).

A potential beneficial side effect of this approach is that our Servlet and Spring MVC support implementations would be more alike or even converge to the same thing if possible, hopefully reducing total code involved.

**Comment by mzumbadoate** [comment]
github branch 542_filter_based_render_spring_mvc

**Comment by dogeared** [comment]
Note: When a feature is disabled, the filter needs to tlet the request flow through  per spec [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/requests.md)

**Comment by lhazlewood** [comment]
This was looking to be fairly complicated and not desirable such that we might not implement it (our Laravel support opted to not do this for similar reasons).

However, one approach might be to make a dispatcher servlet that is used by our internal implementation only, and the ControllerFilter can delegate to that when it is determined that we should process the request:

http://stackoverflow.com/questions/23049736/working-with-multiple-dispatcher-servlets-in-a-spring-application

I'll look into this solution a bit more after seeing how our spa/js support goes.

**Comment by dogeared** [comment]
@lhazlewood - would you circle back to this? @bretterer - where did you land with Laravel integration for this?

**Comment by dogeared** [comment]
Currently implemented in `AbstractStormpathWebMvcConfiguration.stormpathHandlerMapping` and handlers. Should instead be filters to manage whether or not the request should fall through.

**Comment by dogeared** [comment]
Rough steps to implement:

1. Start with Spring (since it uses JSP)
2. Then do Spring Boot to incorporate Thymeleaf

Next:

1. convert `AbstractStormpathWebMvcConfiguration.stormpathHandlerMapping` to `DefaultFilterChainResolverFactory ` style
2. Use `InternalResourceView` as a guide for returning Thymeleaf template views.

**Comment by lhazlewood** [comment]
All relevant 542 branches (plus ID SIte & Saml for servlet/spring/security) have been merged to master, so I'm considering this closed.  @dogeared or @mrioan if you feel otherwise, please re-open.
