### ISSUE TITLE
Create an AuthenticationAccountStoreResolver for runtime resolution

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#543]
Currently we only have a `DisabledAccountStoreResolver`. We need to have a runtime account store resolution - i.e. what account store to target when a certain tenant is in use.  For example, if I visit https://foo.myapp.com the 'foo' account store should be targeted during authentication attempts, whereas for https://bar.myapp.com, the 'bar' account store should be targeted.

**Comment by dogeared** [comment]
@mrioan - The organization resolver code that we already have will lookup the organization name key based on the sub-domain and target that organization when authenticating. It's seems what you are proposing would (perhaps) conflict with this?

**Comment by dogeared** [comment]
Call it: `AuthenticationAccountStoreResolver`. Should be able to use a default strategy or one provided as an override by user.

**Comment by jarias** [comment]
@dogeared @mrioan Is this describe in the spec?,  cause what Micah is saying is that we resolve organization based on the subdomain already, isn't it kind of confusing to be able to resolve both organization and account store based on the sub domain?

I'm just trying to understand the logic before someone picks it up.

**Comment by jarias** [comment]
Also I don't know if the account store name is domain friendly cause I can create directories with . in their name for example.

**Comment by dogeared** [comment]
@jarias - This is not in the spec, but we identified it as important for 1.0 since multi-tenancy support has been around for so long and since we might introducing breaking changes if we try to tackle this after 1.0. The domain resolver code that we already have can have a base domain set. So, if you had a domain like: `foo.bar.baz.com`, you could set the base domain as: `bar.baz.com` and then it would know to only use the `foo` for account store lookup.

**Comment by jarias** [comment]
@dogeared Besides creating the resolver, I guess we need to use it in registration and login, right?

**Comment by jarias** [comment]
According to what we talk this week, only the hooks to call the resolver are going to be added to the 1.0.0 so users can start using it with their own impl, and for the 1.0.1 release we could add a couple of impl of our own.
