### ISSUE TITLE
Add support for client_credentials OAuth grant type

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#569]
Per the [framework spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/authenticators.md), we need a `OAuthClientCredentialsRequestAuthenticator`

The framework spec also references oauth support [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/oauth2.md).

**Note:** We currently have support for the `client_credentials` `grant_type` in the `BasicAuthenticationScheme`. We need to integrate this functionality into the `/oauth/token` endpoint.

**Comment by mzumbadoate** [comment]
#570 is blocking this ticket
