### ISSUE TITLE
Update all authenticators to conform to the framework spec

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#570]
Per [framework spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/authenticators.md), our authenticators should be named as:

* BasicRequestAuthenticator
* OAuthBearerRequestAuthenticator
* OAuthClientCredentialsRequestAuthenticator
* OAuthPasswordRequestAuthenticator
* OAuthRefreshTokenRequestAuthenticator
* OAuthStormpathTokenRequestAuthenticator

Note: as part of this issue, all occurrences of `Oauth...` should be refactored to `OAuth...` per framework spec and per naming convention in the [OAuth2 spec](https://tools.ietf.org/html/rfc6749)

Note: #569 addresses implementing the client_credentials grant_type

**Comment by mrioan** [comment]
@Micah, looking for a 2nd pair of eyes here, based on [this](https://github.com/stormpath/stormpath-sdk-spec/pull/10/files) I should not use `OAuthPasswordRequestAuthenticator ` but `OAuthPasswordGrantRequestAuthenticator ` instead, right?
