### ISSUE TITLE
Email Verification: Support application/json flow for GET and POST

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#573]
per [spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/email-verification.md#get-requests-that-prefer-applicationjson), need to update the existing codebase to support GET and POST application/json type requests and return proper responses.

**Comment by dogeared** [comment]
Hey @mzumbadoate.

I have done some UATs and these are my findings:

Using `spring-boot-webmvc` example
--------------------------------------------------

After registration, if `stormpath.web.register.autoLogin = true` I do not see the account cookie after verifying with spToken

Using Servlet Example
------------------------------

- I do not see the "We sent you a verification email screen" after registration. I see "Didn't receive your account verification email?".
- After succesful verification I am not being redirected to `/login?status=verified`
- If `stormpath.web.register.autoLogin = true` I do not see the account cookie after verifying with spToken

Using spring-security-webmvc Example
----------------------------------------------------
- I do not see the "We sent you a verification email screen" after registration. I see "Didn't receive your account verification email?".
- If `stormpath.web.register.autoLogin = true` I do not see the account cookie after verifying with spToken

Tests
-------
I see there are some tests that still use `stormpath.web.verify.nextUri` rather than `stormpath.web.verifyEmail.nextUri`. 

1. Why didn't those tests fail? Please be sure that they fail. Otherwise they are not working and we cannot rely on them.
2. Please fix those afterwards 

I still did not do any Json UAT. I think these findings have to be fixed before I can UAT JSON support.

Back to you @mzumbadoate

**Comment by lhazlewood** [comment]
@dogeared are you going to re-review this now that it is no longer in-progress?
