### ISSUE TITLE
Refactor /logout to respond only to POSTs and to support JSON requests

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#578]
per the framework spec [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/logout.md).

- We need to change the current behavior that supports GET for logout
- We need to add support for `application/json` requests per the spec

Note: We will need to have messaging around the API change for current users. This issue should be added to the [migration guide](https://github.com/stormpath/stormpath-sdk-java/issues/579)

**Comment by jarias** [comment]
This ticket was done out of the SPA branch that's why the PR is against it and not master.
