### ISSUE TITLE
Create a deprecation and migration guide

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#579]
The 1.0 release removes a lot of deprecated APIs and alters a number of APIs.

The guide proposed in this issue enumerates each of these changes and provides new interfaces and/or alternatives.

**Comment by dogeared** [comment]
covered by https://github.com/stormpath/stormpath-sdk-java/wiki/1.0-Configuration-Changes-&-Additions-Guide

**Comment by adamstormpath** [comment]
@dogeared  Is your doc update above sufficient? What's left to do in this ticket?

**Comment by adamstormpath** [comment]
@dogeared per discussion w/ team, we feel like this migration guide may no longer be necessary , should we drop this task?
