### ISSUE TITLE
Support properties and functionality for /forgot with JSON requests

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#581]
per framework spec [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/password-reset.md).

- Change `stormpath.web.forgot.*` to `stormpath.web.forgotPassword.*`
- Add support for `application/json` requests
- Ensure that the current HTML implementation conforms to the framework spec

**Comment by mraible** [comment]
The first item in this issue was completed as part of #617.
