### ISSUE TITLE
Add support for /register per the framework spec

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#583]
per framework spec [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/registration.md).

- We need to verify that the current HTML responses conform to the spec
- We need to add in the `stormpath.web.register.enabled` property
- We need to add support for `application/json`, including being able return the register model.
- We need to expand on the currently supported properties for specifying form fields. These properties need to be able to be in yaml format as specified in the spec
- We need to support custom fields and have those custom fields populate customData on submit, as specified in the spec

**Comment by BernhardLenz** [comment]
I believe this is a very important feature for Stormpath to be able to customize the registration form to capture custom fields such as Notification Preferences, Male/Female, Birth Date, Customer/Vendor etc etc. This enhancement should be treated as a top priority.

**Comment by mzumbadoate** [comment]
blocked by #577
