### ISSUE TITLE
User Agent has a few issues

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#591]
- I see `user-agent:stormpath-sdk-java/${project.version} java/1.8.0_60 Mac OS X/10.10.5` when it should be `user-agent:stormpath-sdk-java/1.0.0.RC-SNAPSHOT java/1.8.0_60 Mac OS X/10.10.5`

- Additionally, when running `spring-webmvc` example the User Agent is missing something like `stormpath-spring-webmvc/1.0.0.RC-SNAPSHOT`. It looks like this right now:

```
stormpath-servlet-java/1.0.0.RC-SNAPSHOT stormpath-sdk-java/1.0.0.RC-SNAPSHOT spring/4.2.6.RELEASE tomcat/7.0 java/1.8.0_60 Mac OS X/10.11.4
```

- Spring Security Spring WebMVC returns `stormpath-spring-security/unknown`

**Comment by lhazlewood** [comment]
I'm not sure if the version is pulled in correctly on SNAPSHOT versions.  Check out a release version and see if it works.  If so, I'm not sure this would be a high prio.  If we see this behavior on a release version, it does need to be fixed.

**Comment by mraible** [comment]
@mrioan Do you have steps to reproduce this issue? I didn't see it when working on #478.

**Comment by jarias** [comment]
Issues 1 and 3 are cause when the war is build by intellij instead of maven, I pushing a PR to include the second bullet that @mrioan  mention
