### ISSUE TITLE
stormpath.web.accessToken.origin.authorizer.originUris expects URIs separated by space instead of comma

### ISSUE THREAD

**Issue by lehphyro** [stormpath/stormpath-sdk-java#595]
The error message that one gets when an Origin is not allowed is generated by the following template:
"Unauthorized {} header value: {}.  If this is unexpected, you might want to specify one or more comma-delimited URLs via the {} property.", but the configuration must be space-delimited.

**Comment by dogeared** [comment]
Hi @lehphyro - Thanks for posting this. I tested this and it works *only* when you have comma delimited values. For instance:

```
stormpath.web.accessToken.origin.authorizer.originUris = http://bob.bom, http://alice.com
```

When you use spaces, it gets read in as a single string. Based on this, I am going to close this issue.
