### ISSUE TITLE
Support JSON config

### ISSUE THREAD

**Issue by mraible** [stormpath/stormpath-sdk-java#596]
Per framework spec [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/configuration.md) and [here](https://github.com/stormpath/stormpath-framework-spec/blob/master/web-config.yaml).

We need to support JSON config in:

* core sdk
* servlet plugin

Spring and Spring Boot do not need to support JSON as users can use their [default configuration mechanisms](https://github.com/stormpath/stormpath-sdk-java/issues/571#issuecomment-207492992).

**Comment by dogeared** [comment]
removed core sdk support from the scope of this issue. Core SDK will be addressed in #607.

**Comment by mraible** [comment]
Support for JSON config is now in PR #617.
