### ISSUE TITLE
Enhance Core SDK to support .properties configuration

### ISSUE THREAD

**Issue by mraible** [stormpath/stormpath-sdk-java#597]
The Core SDK should allow users to specify `.properties` in the following locations to override defaults.

1. `classpath:com/stormpath/sdk/config/stormpath.properties`
2. `classpath:stormpath.properties`
3. `$HOME/.stormpath/apiKey.properties`
4. `$HOME/.stormpath/stormpath.properties`
5. `System.getProperty("user.dir") + File.separator + "apiKey.properties"`
6. `System.getProperty("user.dir") + File.separator + "stormpath.properties`

NOTE: The first file does not currently exist, so it will need to be created with all the [defaults](https://github.com/stormpath/stormpath-sdk-spec/blob/master/specifications/config.md#default-configuration).

See https://github.com/stormpath/stormpath-sdk-java/wiki/Overriding-Default-Configuration for additional information.

**Comment by mraible** [comment]
Currently, [ClientApiKeyBuilder](https://github.com/stormpath/stormpath-sdk-java/blob/master/impl/src/main/java/com/stormpath/sdk/impl/api/ClientApiKeyBuilder.java) only supports [one of these mechanisms](https://github.com/stormpath/stormpath-sdk-java/blob/master/impl/src/main/java/com/stormpath/sdk/impl/api/ClientApiKeyBuilder.java#L38):

`System.getProperty("user.dir") + File.separator + "apiKey.properties"`

@lhazlewood To fix this issue, should this class be enhanced to support all 6 of the above locations?

**Comment by lhazlewood** [comment]
@mraible yes please, we need all 14 locations to be supported as defined here: https://github.com/stormpath/stormpath-sdk-java/wiki/Overriding-Default-Configuration

**Comment by mraible** [comment]
@lhazlewood Just so we're on the same page, it seems like the Core SDK should be enhanced to support the 6 locations above, while the servlet SDK will support the other 8.

**Comment by mraible** [comment]
Nevermind, I see what you mean in that all locations mentioned in https://github.com/stormpath/stormpath-sdk-java/wiki/Overriding-Default-Configuration#core-sdk-only should be supported. However, #598 is for adding YAML support and #596 should cover the JSON files.

**Comment by lhazlewood** [comment]
Yeah, and just for the sake of clarity at the risk of being pedantic :)

When only the core SDK is used, we need to check [14 locations](https://github.com/stormpath/stormpath-sdk-java/wiki/Overriding-Default-Configuration#servlet-integration).

When the servlet integration is used, we need to check [19 locations](https://github.com/stormpath/stormpath-sdk-java/wiki/Overriding-Default-Configuration#servlet-integration).

When Spring or Spring Boot are in the mix, they have their own config mechanisms as documented in that same wiki page.

**Comment by mraible** [comment]
See PR https://github.com/stormpath/stormpath-sdk-java/pull/607/files for my first attempt at this. Is this the right place to put this reading of the default configuration for client? Also, please see todo comments for next steps.

**Comment by mraible** [comment]
I've closed PR #607 and created #617 to solve this issue. Please review when you have a moment. My biggest concern is if all the properties from `web.stormpath.properties` should be added to `extensions/spring/boot/stormpath-webmvc-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json`. I started this process, but did not finish it. The hardest part will likely be adding descriptions for each key.

https://github.com/stormpath/stormpath-sdk-java/pull/617/commits/aeee45b7164e0cb89ec6628c32f8df44c88b8cf3
