### ISSUE TITLE
When posting to /oauth/token and the request has a cookie the operation is not completed

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#612]
In Spring Security (I tried with with Spring Boot but Spring should also be problematic) if a request to `/oauth/token` is received which has a valid `cookie` then the new access token is not obtained and we return `403`.

This is not specified in our SPEC but Edward suggested we should basically overlook (and overwrite?) the cookie when we see a post to `/oauth/token` .

I am not sure this problem exists in a non-Spring Security scenario.

**Comment by dogeared** [comment]
Need to revalidate against master - may have been resolved.

**Comment by dogeared** [comment]
Regardless of the resolution here, we should not be returning a `403`

**Comment by jarias** [comment]
Looks like you where right @dogeared this is already fix, I test it out in all extensions and it work. Looking at spring security in particular looks like this are the lines that fixed:

https://github.com/stormpath/stormpath-sdk-java/blob/master/extensions/spring/stormpath-spring-security-webmvc/src/main/java/com/stormpath/spring/config/StormpathWebSecurityConfigurer.java#L319

I'm going to add a TCK test if non exists just to have more coverage.

**Comment by jarias** [comment]
Ref TCK PR https://github.com/stormpath/stormpath-framework-tck/pull/295

For some reason waffle didn't link it

**Comment by lhazlewood** [comment]
Big 👍  to adding to the TCK.
