### ISSUE TITLE
Something weird with Stormpath and Spring Security (WebSecurityConfigurerAdapter)

### ISSUE THREAD

**Issue by lcollet** [stormpath/stormpath-sdk-java#618]
When trying to secure my rest api, the stormpath call seems to hide my security config.

Without Stormpath call :
`http
	      	.authorizeRequests()
	        .antMatchers("/").permitAll().and().authorizeRequests().antMatchers("/users*").authenticated();`

`$ curl -X GET http://localhost:8080/users
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   102    0   102    0     0   6375      0 --:--:-- --:--:-- --:--:--  6375{"timestamp":1462561507521,"status":403,"error":"Forbidden","message":"Access Denied","path":"/users"}
`

With stormpath call : 
`    	http.apply(stormpath()).and()
	      	.authorizeRequests()
	        .antMatchers("/").permitAll().and().authorizeRequests().antMatchers("/users*").authenticated();`

`$ curl -X GET http://localhost:8080/users
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

`

I'm expecting a 403 error... what's happening ?
fyi, the same behavious occurs when following your tutorial : https://stormpath.com/blog/build-spring-boot-spring-security-app

I'm just building a rest api so i'm not using thymeleaf . 
Stormpath versions : 1.0.RC8.6 & 1.0.RC9.1

**Comment by mrioan** [comment]
hey @lcollet . Our Spring Security integration will automatically redirect the request to the login screen since `/users*` requires authentication. Curl by default does not follow redirects. Could you please retry with `curl -L -X GET http://localhost:8080/users` ? (-L instructs curl to follow redirects)

**Comment by lcollet** [comment]
You're right!

`$ curl -L -X GET http://localhost:8080/users
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   109    0   109    0     0   1172      0 --:--:-- --:--:-- --:--:--  1172{"timestamp":1462570114326,"status":404,"error":"Not Found","message":"No message available","path":"/login"}
`
