### ISSUE TITLE
SpringCache using putIfAbsent for the put operation

### ISSUE THREAD

**Issue by demboos** [stormpath/stormpath-sdk-java#636]
com.stormpath.spring.cacheSpringCache is using org.springframework.cache.Cache.putIfAbsent in the implementation of the put method. This causes problems with values not being updated in cache at all (because they already exist in the cache).

On the contrary, the DefaultCache implementation (which uses a simple Map), uses a simple Map.put operation.

Shouldn't the SpringCache implementation be using simple put as well ?

**Comment by lhazlewood** [comment]
Indeed it should. Thanks for the ticket!
