### ISSUE TITLE
Fix links to the REST Guide

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#639]
There are some hardcoded links that need to be updated. We need to look at this manually and update where necessary.  

The pattern to look for is: /rest/product-guide/#

Below is a list of common issues found for some SDKs. Not all of them might exist in the Java SDK.

### Verifying email addresses
- Old location: /rest/product-guide/#verify-an-email-address
- New location: /rest/product-guide/latest/accnt_mgmt.html#how-to-verify-an-account-s-email

### Resetting Password
- Old location: /rest/product-guide/#reset-an-accounts-password
- New location: /rest/product-guide/latest/accnt_mgmt.html#password-reset

### Custom Data
- Old location: /rest/product-guide/#custom-data
- New location: /rest/product-guide/latest/accnt_mgmt.html?highlight=customdata#how-to-store-additional-user-information-as-custom-data

### Create Account
- Old location: /rest/product-guide/#account-create
- New location: /rest/product-guide/latest/accnt_mgmt.html#add-a-new-account-to-a-directory

### Import Account with an existing password hash
- Old location: /rest/product-guide/#create-an-account-with-an-existing-password-hash
- New location: /rest/product-guide/latest/accnt_mgmt.html#importing-accounts

### Default Account Store
- Old location: 
- New location: https://docs.stormpath.com/rest/product-guide/latest/accnt_mgmt.html#add-to-app-or-org

### Link Expansion
- Old location: /rest/product-guide/#link-expansion
- New location: /rest/product-guide/latest/reference.html#links

**Comment by mraible** [comment]
@mrioan Where does the documentation reside to fix this? It doesn't seem to be in this repo.

**Comment by mraible** [comment]
PR created at https://github.com/stormpath/stormpath.github.io/pull/264.
