### ISSUE TITLE
Pagination is broken when the items in the list are modified while iterating it

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#640]
## A user reported:

I'm using the Java SDK to page through accounts based on a query. Specifically, I'm looking for accounts that are disabled, because I need to enable some of them.

The problem I encountered is that I would iterate through the list but not find all the accounts I needed to fix.

I suspect that it's because I'm switching the status to enabled as I iterate through them, and the list of accounts it's paginating through is not static (i.e. it loads the next set based on the criteria, which will yield a different list and the offset then jumps past accounts that I haven't actually visited yet).
## Workaround 1

Modify all the accounts without saving. Then, save them once the whole list has been processed

```
        AccountList accounts = application.getAccounts(acountCriteria);
        List<Account> accountsToSave = new ArrayList<Account>();
        for (Account account : accounts) {
            if (needsUpdate(account)) { //some condition to know which account needs to be modified
                update(account); //modify the account BUT DO NOT SAVE IT
                accountsToSave(account);
            }
        }

        //Now you can save the edited accounts
        for (Account account : accountsToSave) {
            account.save();
        }
```
## Workaround 2

Return the whole list (all the items from all the pages) into an array first. And them, modify them.

NOTE: this has worst performance than Workaround 1

```
        AccountList accounts = application.getAccounts(acountCriteria);
        List<Account> allAccounts = new ArrayList<Account>(accounts.getSize());
        for (Account account : accounts) {
            allAccounts.add(account);
        }

        //Now you can edit the accounts in allAccounts
        for (Account account : allAccounts) {
            //edit account here
            if (needsUpdate(account)) { //some condition to know which account needs to be modified
                update(account);
                account.save();
            }
        }
```

**Comment by dogeared** [comment]
FYI, this is a know issue across the SDKs. @rdegges and @josebarrueta can provide some more background.

**Comment by jarias** [comment]
I actually wonder if there is anything we can do really without heavily modify the API or SDKs.

@rdegges have you deal with this in python?

Maybe some batch type operation where the actual save for each account is not done till the end of the iteration it would be similar to workaround #1 but do it internally in the SDK and could also be an a async operation.

@lhazlewood @mrioan any feedback?

I'm going to mark this as blocked till we have some discussion around it.

**Comment by rdegges** [comment]
I've ran into this many times, particularly around deleting accounts. Either strategy #1 or #2 is acceptable, #2 being the only option if you want to delete all accounts in a directory / application.

I've spoken with people about this before, there are various ways to fix this, but almost all require server-side functionality, eg:

- Streaming JSON w/ server-side DB cursors.
- Webhooks w/ server-side DB cursors.
- Improved pagination functionality to include a frozen query state based on hash values (most likely still requires DB cursors).

**Comment by dogeared** [comment]
Based on @rdegges feedback, I think we should kick this out of the 1.0 release. We can provide the workaround for the user that raised the issue.

One other approach I've seen is to:

1) grab the first page
2) delete just those elements
3) repeat from 1 until the returned collection is < pageSize
4) delete the final chunk

**Comment by lhazlewood** [comment]
👍  to delaying until after 1.0

**Comment by mrioan** [comment]
We consider the developer is responsible to properly handling collections. That is, the collection must not be modified while it is being iterated. Although this could be enhanced this is actually not a bug therefore this issue can be closed.
