### ISSUE TITLE
Figure out how to handle or document i18n message in form field config

### ISSUE THREAD

**Issue by jarias** [stormpath/stormpath-sdk-java#645]
Currently the Java web integration provides i18n support, so in order to configure extra fields for /login or /register the values for label and placeholder should be 18n keys otherwise the value won't render correctly in the view

Example:

```
stormpath.web.register.form.fields.CustomField.type = text
stormpath.web.register.form.fields.CustomField.label = CustomField
stormpath.web.register.form.fields.CustomField.enabled = true
stormpath.web.register.form.fields.CustomField.visible = true
stormpath.web.register.form.fields.CustomField.required = true
stormpath.web.register.form.fields.CustomField.placeholder = CustomField
```
Would render in servlet `!CustomField!` and `??CustomField_en_US??` on Spring

Options:

1. Clearly document that the values should be i18n keys in the i18n.properties file.
2. Do a fallback behavior if the key is not there use the value as it is so the example above would work without any extra effort by the user.

**Comment by mraible** [comment]
I'm unable to get custom fields to render on the register form. If I create a src/main/resources/stormpath.properties with the following in examples/servlet and start it with mvn tomcat7:run, I don't see any custom fields.

```
stormpath.web.register.form.fields.CustomField.type = text
stormpath.web.register.form.fields.CustomField.label = CustomField
stormpath.web.register.form.fields.CustomField.enabled = true
stormpath.web.register.form.fields.CustomField.visible = true
stormpath.web.register.form.fields.CustomField.required = true
stormpath.web.register.form.fields.CustomField.placeholder = CustomField
```

**Comment by mraible** [comment]
@jarias How do I reproduce this problem for Spring? I put the keys above into `examples/spring-webmvc/src/main/resources/stormpath.properties` and I don't see any custom fields when I start the app using `mvn tomcat7:run`.

**Comment by mraible** [comment]
@jarias Nevermind, I figured it out. I needed to put the properties in `examples/spring-webmvc/src/main/resources/application.properties`
