### ISSUE TITLE
Array type properties not working correctly

### ISSUE THREAD

**Issue by jarias** [stormpath/stormpath-sdk-java#650]
the produces property and the fieldOrder property for login and register are describe as lists in the spec.

In the servlet extension the defaults are written as:

```
stormpath.web.produces[0] = application/json
stormpath.web.produces[1] = text/html
```

But the ExpressionConfigReader lacks the ability to read this and return a proper list

Also in Spring we asume "," separated values to describe lists which might break users custom configuration

```java
@Value("#{ @environment['stormpath.web.produces'] ?: 'application/json, text/html' }")
protected String produces;
```
In this case we asume is a single string which is later parse using `MediaType.parseMediaTypes(..)`

For the fieldOrder we delegate the work to Spring to get a `String[]` but I don't know if it supports the prop[INDEX] notation.

see AbstractSpringControllerConfigResolver.java

```java
Arrays.asList(env.getProperty("stormpath.web." + getControllerKey() + ".form.fields.fieldOrder", String[].class, getDefaultFieldOrder()))
```

**Comment by jarias** [comment]
verifyPropertiesInSpecAreInDefault test is been disable cause of this.

https://github.com/stormpath/stormpath-sdk-java/blob/master/extensions/servlet/src/test/groovy/com/stormpath/sdk/servlet/config/SpecConfigVersusWebPropertiesTest.groovy#L41

**Comment by mrioan** [comment]
@jarias In summary, you are saying that Servlet is not spec complaint with regards to the `stormpath.web.produces` property ? Is that the real issue?

**Comment by lhazlewood** [comment]
Unless I'm missing something, `stormpath.web.produces` should be a comma-delimited list of supported MediaType values and should not use array notation.

**Comment by jarias** [comment]
@lhazlewood not according to the spec its configure as a list.

```
stormpath:
  web:
    produces:
      - application/json
```

**Comment by lhazlewood** [comment]
Ah, right you are!

While this is true for YAML, shouldn't it be a comma-delimited list for .properties?  Array notation in .properties files isn't really desirable, no?

**Comment by jarias** [comment]
@lhazlewood Yeah that's what we are changing also trying to make it consistent between YAML and .properties

**Comment by lhazlewood** [comment]
Wait I'm confused.  IIUC:

YAML:  you configure a list (with `-` notation)
Properties: you configure a String that is comma-delimited.  No `[n]` array notation.

Is this correct?

**Comment by mraible** [comment]
I copied Spring's YAML parser, which creates indexed properties. My PR for this issues changes our YAML to Properties parser to returned a single comma-delimited value.
