### ISSUE TITLE
Do NOT require Origin header for json requests

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#659]
currently, an Origin header is always required for POSTs.

if the Accept header is explicitly `Accept:application/json` or the `produces` property favors json, the `Origin` header should not be required.

**Comment by mraible** [comment]
@dogeared Is there an existing integration test I can modify to test this, or a POST request you'd recommend?

**Comment by mraible** [comment]
Here are the `curl` commands I used to test this. Will look into writing integration tests tomorrow.

Should not return an origin error:
```
curl -X POST --data 'grant_type=password&username=foo&password=bar' \
         -H 'Origin: http://localhost:8080' http://localhost:8080/oauth/token
```

Should return an origin error:
```
curl -X POST --data 'grant_type=password&username=foo&password=bar' \
        http://localhost:8080/oauth/token
```

Should not return an origin error:
```
curl -X POST --data 'grant_type=password&username=foo&password=bar' \
        -H 'Accepts: application/json' http://localhost:8080/oauth/token
```

**Comment by lhazlewood** [comment]
We shouldn't remove the Origin header check - it is useful for basic security assertions and has nothing to do with POSTs.

**Comment by lhazlewood** [comment]
I'll rephrase - it limits who can POST from where, which aids in basic browser security assertions.  This is a good check to have, and is completely independent of content type negotiation, so I'm not sure why content types were brought up as a reason for removing the Origin check.

**Comment by lhazlewood** [comment]
> curl -X POST --data 'grant_type=password&username=foo&password=bar' \
        -H 'Accepts: application/json' http://localhost:8080/oauth/token

*should* return an Origin error.

**Comment by dogeared** [comment]
@lhazlewood - in the context of the Framework TCK and the other integrations, I currently check for the `Origin` header. `Oauth2IT` is a good example.

The other evangelists thought that it didn't make sense in the context of a mobile app to require an `Origin` header. What should the Origin be for an iOS or Android app?

The thought, then, was that in the case of JSON requests, this requirement should be relaxed.

It is worth noting that having the `Origin` header in the tests does not hurt the other integrations using the TCK, but there was an overall feeling amongst the evangelists that it shouldn't be required in this case.

**Comment by lhazlewood** [comment]
@dogeared if that's the case, we should disable the Origin check when the user agent matches iOS or Android, no?

**Comment by dogeared** [comment]
Added blocked label until we work it out on the SDK planning meeting.

**Comment by lhazlewood** [comment]
I don't know that this is 'blocked' since the 1.0 spec doesn't require this.  I'll advocate adding this logic in to the spec, but I doubt it would make it into 1.0 - probably a 1.1 spec.
