### ISSUE TITLE
Enforce custom field values against custom data on login form

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#668]
If you add these custom field definitions to `stormpath.properties` in the case of servlet or `application.properties` in the case of Spring:

```
stormpath.web.login.form.fields.CustomField.type = text
stormpath.web.login.form.fields.CustomField.label = Custom Field Login
stormpath.web.login.form.fields.CustomField.enabled = true
stormpath.web.login.form.fields.CustomField.visible = true
stormpath.web.login.form.fields.CustomField.required = true
stormpath.web.login.form.fields.CustomField.placeholder = Custom Field Login

stormpath.web.register.form.fields.CustomField.type = text
stormpath.web.register.form.fields.CustomField.label = Custom Registration Field
stormpath.web.register.form.fields.CustomField.enabled = true
stormpath.web.register.form.fields.CustomField.visible = true
stormpath.web.register.form.fields.CustomField.required = true
stormpath.web.register.form.fields.CustomField.placeholder = Custom Registration Field
```

You will find that on registration, the custom field value will be stored as custom data.

On login, the custom field will be on the login form, but it's value is *not* enforced against the value in custom data.

**Comment by mraible** [comment]
@dogeared How would someone define a customData field for the login form? 

On a related note, how do I know it's a custom data field (for logic in `LoginController`)?

**Comment by jarias** [comment]
According to spec 

> Additional configured login form parameters will be ignored by the framework integration, but should be exposed to the application via the pre and post login handlers.

So this ticket is not actually valid
