### ISSUE TITLE
/me endpoint results in NPE for certain integrations

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#675]
using this to test:

```
http localhost:8080/me
```

**PASS**: `Servlet` (returns: `HTTP/1.1 401 Unauthorized`)

**FAIL**: `Spring WebMVC` (NPE, DefaultAccountModelFactory:75; MeController:50)

**FAIL**: `Spring Security Spring WebMVC` (NPE, DefaultAccountModelFactory:75; MeController:50)

**FAIL**: `Spring Boot WebMVC` (NPE, DefaultAccountModelFactory:75; MeController:50)

**FAIL**: `Spring Security Spring Boot WebMVC` (NPE, DefaultAccountModelFactory:75; MeController:50)

**Comment by mrioan** [comment]
Mimicking what the Servlet is doing we should be returning `401` when not authenticated for all the integrations
