### ISSUE TITLE
Returning `400` when should be returning `401`

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#681]
In cases where there is a failure in bearer token authorization, the status code returned should be `401`.

Steps to reproduce:

1) get an access and refresh token

```
http -f POST localhost:8080/oauth/token \
grant_type=password username=<valid email> password=<valid password>
```

2) save the returned `refresh_token` to a local variable for later use

```
REFRESH_TOKEN=<refresh_token returned from step 1>
```

3) hit the `/me` endpoint with the refresh token as a bearer token

```
http localhost:8080/me Authorization:"Bearer $REFRESH_TOKEN"
```

This should fail and it does. However, the status returned currently is `400` and it should be `401`.

**Comment by lhazlewood** [comment]
We should not pass through the Stormpath response code directly to the application end-user - it reflects a different scenario.

**Comment by dogeared** [comment]
Thanks @lhazlewood. I updated the comment above to reflect the case where we are returning a `400` and it should be a `401`. I also have a PR for this: #686
