### ISSUE TITLE
`/next` in querystring should take precedence over default or property settings

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#683]
Steps to reproduce:

1) Start `Spring WebMVC` example in the Java SDK project

2) Browse to: `http://localhost:8080/login?next=/foo`

3) Enter valid `username` and `password`

4) You will *not* be redirected to `/foo` as you should be

**Comment by jarias** [comment]
The next query param is a way to do it but the spec doesn't actually specifies that it should be a next query param.

> If the request cannot be authenticated, how to respond will depend on the content preference of the request:

> text/html - respond with a 302 redirect to the login view, and preserve the current URL so the user can be redirected to their original destination after login. If possible, use built-in features of the host framework to do this securely; otherwise, use a secure method of passing the destination URL forward.

I just raise a question here cause while I was doing the web extension for Go I couldn't find anywhere in the spec where it mentions that there should be a next query param to override the redirect, the only thing I found was the quote above.
