### ISSUE TITLE
The SDK's i18n support is inconsistent with the e-mail workflows

### ISSUE THREAD

**Issue by george-hawkins-aa** [stormpath/stormpath-sdk-java#690]
The individual SDKs (including this one) go to quite a lot of trouble to support i18n. However this is rendered somewhat pointless by the fact that the e-mail workflows provide no support for i18n.

This is an e-mail workflows issue rather than a Java SDK issue but there is no public repo for us to track features related to what users can (or can't in this case) configure via the [api.stormpath.com](https://api.stormpath.com/login) site.

This issue is covered in the fairly vague "[Can I localize Stormpath workflow e-mails?](https://support.stormpath.com/hc/en-us/articles/203937263-Can-I-localize-Stormpath-workflow-e-mails-)" but developers have no visibility on the roadmap.

So I'm logging this issue here in the hope that somewhere more appropriate opens up for issues related to the service delivered by Stormpath itself, rather than just the SDKs used for accessing it, and that developers then get some visibility on progress related to this issue.

**Comment by omgitstom** [comment]
Hi George,

I manage product @ stormpath and we have talked before.  Stormpath has an idea portal here for our customers to weigh in on what is important to them:

http://ideas.stormpath.com

This issue has already been logged and can be viewed here:
http://ideas.stormpath.com/ideas/IAM-I-78

I hear you loud and clear that our roadmap isn't visible, and my vision is to be clear on the ideas portal what is planned and currently being worked on, and what is shipped.

Thanks,
Tom
