### ISSUE TITLE
Refactor access token and refresh token code to take advantage of new type header

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#696]
JWT's from the backend now include `stt` (stormpath token type) claim in the header.

We are currently checking for the presence of the `rti` claim in the body to determine if a token is an access token.

We now have explicit types in the JWT header to determine type.

`stt` will be `access` for an access token and `refresh` for a refresh token

**Comment by mraible** [comment]
Is this as simple as changing `DefaultAccessToken.java` from using this:

```java
// token *must* have an rti claim to be an access_token
// otherwise, it may be a refresh_token trying to be passed off as an access_token
Assert.isTrue(Strings.hasText((String) claims.get("rti")));
```

to this?

```java
String tokenType = (String) claims.get("stt");
Assert.isTrue(tokenType.equals("access"));
```
