### ISSUE TITLE
Default view templates should react to disabled views

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#708]
For example, the login.html template (or .jsp for servlet) should *not* have a link to register if `stormpath.web.register.enabled = false`.

All templates should react to disabled views and not display html content that reflect those views.

**Comment by lhazlewood** [comment]
the 708-view-enhancements branch has the latest on this - the LoginController and the thymeleaf template have been updated to react as necessary.  The login.jsp still needs to be updated.

**Comment by mraible** [comment]
@lhazlewood Are you still working on this issue or can I grab it?

**Comment by lhazlewood** [comment]
@mraible please grab it - the branch should be up to date and just the .jsp changes should be all that remains.
