### ISSUE TITLE
IDSite not being contacted on logout when CSRF is disabled

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#709]
It was reported that IDSite logout was not being forwarded to IDSite when csrf is disabled using the property:
```
stormpath.web.csrf.token.enabled=false
```
Turning back on csrf tokens re-enabled forwarding to the idsite for logout.

For more info refer to ticket 7777. 
Once it gets solved please notify Colin.

**Comment by jarias** [comment]
Haven't been able to reproduce this exact issue, but I did found that with spring security spring boot extension IDsiste logout wasn't been redirected properly but it didn't have anything to do with CSRF been enable or disabled.
