### ISSUE TITLE
examples/spring-security-spring-boot-webmvc-bare-bones does not load stormpath assets

### ISSUE THREAD

**Issue by mraible** [stormpath/stormpath-sdk-java#711]
![screen shot 2016-06-16 at 10 46 41 am](https://cloud.githubusercontent.com/assets/17892/16125198/c96f1e4c-33af-11e6-9868-e976664f6646.png)

**Comment by lhazlewood** [comment]
I'm pretty sure this is a handlermapping order issue.  I'm encountering this same exact issue today in another project.

I believe it will be solved by modifying the `AbstractStormpathWebMvcConfiguration` implementation's `stormpathHandlerMapping()` method by adding a couple of mappings:

```java
mappings.put(`/assets/js/stormpath.js`, aResourceHttpRequestHandlerInstance);
mappings.put(`/assets/cs/stormpath.css`, aResourceHttpRequestHandlerInstance);
```

**Comment by lhazlewood** [comment]
I had to do this as a workaround:

```java
@Configuration
public class WebConfig extends WebMvcConfigurerAdapter {

    @Value("${stormpath.web.handlerMapping.order}")
    private int stormpathHandlerMappingOrder = -300;

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.setOrder(stormpathHandlerMappingOrder);
        registry.addResourceHandler("/assets/js/stormpath.js").addResourceLocations("classpath:/META-INF/resources/");
        registry.addResourceHandler("/assets/css/stormpath.css").addResourceLocations("classpath:/META-INF/resources/");
    }
}
```

**Comment by mraible** [comment]
This only seems to happen when SAML is enabled in `application.properties`:

```
stormpath.web.callback.enabled=true
```

The CSS and JS is loaded fine otherwise. 

![image](https://cloud.githubusercontent.com/assets/17892/16402501/8d851dbe-3c88-11e6-8826-9efa6f7530e6.png)
