### ISSUE TITLE
Work on TCK test for Spring Security redirection to Login

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#716]
See https://github.com/stormpath/stormpath-framework-spec/issues/114

**Comment by mzumbadoate** [comment]
@mrioan are you talking about creating a new test in the TCK? is this a java-sdk specific test? if yes it will fail in other frameworks right?
I found in Cookie.IT
 /** Reject unauthorized text/html requests with 302 to login route
     * 302 to login route should preserve original URL including query string
     * @see <a href="https://github.com/stormpath/stormpath-framework-tck/issues/36">#36</a>
     * @see <a href="https://github.com/stormpath/stormpath-framework-tck/issues/121">#121</a>
     * @throws Exception
     */
    @Test(groups=["v100", "html"])
    public void unauthorizedHtmlRequestIsForwardedToLogin() throws Exception {

could this work?

**Comment by mrioan** [comment]
Every SDK should redirect to `/login` when going to `/me` when the user is not logged in. If I am not wrong we had this test in the TCK in the past and it was removed. I think @dogeared knows what I am talking about as it was discussed in an evangelists meeting. Micah, can you chime in please?

**Comment by dogeared** [comment]
Use the `more_csrf_and_cookies` branch of the `stormpath-framework-tck` to test that the `/me` endpoint properly redirects to `/login` for all the integrations.

**Comment by dogeared** [comment]
Note: `more_csrf_and_cookies` has been merged to master. You can work off master now.
