### ISSUE TITLE
Ensure that all TCK tests pass

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#733]
OR update the TCK if it is not responding correctly to valid requests.

**Comment by dogeared** [comment]
*Note*: per #542, if there are any SPA fall through tests, we expect that not to work yet.

**Comment by dogeared** [comment]
## TCK Scorecard:

**Note**: accounts for #710 and #756 being merged to master, which has not happened yet.

| Integration  |  Raw Score |  % Pass |
|----------------|:--------------:|---------:|
| Servlet          | 10 of 109   | 91%          |
| Spring WebMVC |  10 of 109 | 91% |

**Comment by dogeared** [comment]
UPDATE: PR https://github.com/stormpath/stormpath-framework-tck/pull/296 fixes `RegisterIT` against Spring Security reducing the number of failures from 24 down to 19. I will update the scorecard once the PR is merged.

**Comment by mraible** [comment]
@dogeared I created a PR to get CookieIT to pass with Spring MVC. I don't think there's a specific ticket for this. https://github.com/stormpath/stormpath-sdk-java/pull/789

**Comment by mraible** [comment]
## TCK Scorecard:

Update: 8/1/2016 around 6pm MST

The results below use the master branch of both  `stormpath-sdk-java` and `stormpath-framework-tck`

| Integration  |  Raw failures |  % Pass | Failures |
|----------------|:--------------:|---------:|---------|
| Servlet          | 0 of 112   | 100%       |         |
| Spring WebMVC |  0 of 112 | 100% |                   |
| Spring Security WebMVC |  9 of 112 | 92% | <ol><li>ErrorsIT.missingEndpointShouldReturn404</li><li>LoginIT.loginFormPreservesValuesOnPostback</li><li>LoginIT.loginHtmlRendersErrorWithoutUsernameAndPassword</li><li>LoginIT.loginRendersErrorOnFailure</li><li>RegisterIT.registerErrorsForUndefinedFieldsHtml</li><li>RegisterIT.registerErrorsOnServerErrorHtml</li><li>RegisterIT.registerErrorsWithEmptyPostBody</li><li>RegisterIT.registerErrorsWithMissingRequiredFormFieldsHtml</li><li>RegisterIT.registerFormPreservesValuesOnPostback</li></ol> |
| Spring Boot WebMVC | 1 of 112 | 99% | CookieIT.cookieExpirationMatchesTokenTtl  |
| Spring Security Spring Boot WebMVC | 2 of 112 | 98% | <ol><li>ErrorsIT.missingEndpointShouldReturn404</li><li>CookieIT.cookieExpirationMatchesTokenTtl</li></ol> |

**Comment by mraible** [comment]
@dogeared I'm unable to reproduce the Spring MVC failures with `LogoutIT`.
