### ISSUE TITLE
Refactor client_credentials grant type to use backend

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#744]
Now that there's backend support for client_credentials, we can refactor our code to use it.

**Comment by mrioan** [comment]
This issue needs to be re-opened because this important comment has been overlooked: https://github.com/stormpath/stormpath-sdk-java/pull/752/files#diff-5bbc2f27f032939cb4d411c7cfcc7c75L253.

In summary `IdSiteResultController#getAccessToken` needs to be updated as well.

**Comment by jarias** [comment]
@mrioan The code was copied as the comment mentions, but the intention was different in the IdSiteResultController we want to do a token exchange to get the access and refresh token, in the client_credentials authentication we use token exchange as a hack to get the access token and then remove the refresh token cause the client credentials grant doesn't return the refresh token. But still the code was duplicated in a 3rd place which is the CookieAuthenticationResultSaver which already takes care of exchange token for TransientAuthenticationResult.

So I did refactor the code but I just wanted to clarify that the use was not the same. So we don't get confused in the code review.
