### ISSUE TITLE
make SAML and ID Site properties and handlers spec compliant

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#748]
ID Site is clearly spelled out here: https://github.com/stormpath/stormpath-framework-spec/blob/master/idsite.md

Dealing with SAML is less clear in the framework spec, but here's what came out of the discussion with the team:

1) There should be a single callback uri defined that handles the result responses from ID Site and from direct SAML interactions. This is the `stormpath.web.callback.uri` property and it defaults to `/stormpathCallback`.

2) If the `stormpath.web.idSite.enabled` property is `true` and the  `stormpath.web.callback.enabled` is `false`, this is a config error that should be caught on startup.

3) If stormpath.web.idSite.enabled` is false and `stormpath.web.callback.enabled` is false AND there are SAML directories mapped to the application, that is also a configuration error. This does not have to be caught on startup. The SAML buttons should not be rendered, BUT there should be an error message in the logs about the config error.

4) The handler for `/StormpathCallback` will determine if it's a callback from ID Site or from a direct SAML interaction and will process accordingly. This information should be clear from the incoming JWT.

**Comment by mraible** [comment]
@dogeared The `stormpath.web.callback.uri` property currently defaults to `/samlResult`. Should this be changed to `/stormpathCallback`? 

https://github.com/stormpath/stormpath-sdk-java/blob/master/extensions/servlet/src/main/resources/com/stormpath/sdk/servlet/config/web.stormpath.properties#L141

**Comment by dogeared** [comment]
Yes.

Micah Silverman

**Comment by mraible** [comment]
@dogeared What should the warning be for the 3rd item? I currently have the following, but it doesn't seem right. We should tell users how to fix it.

`ID Site is disabled and callbacks are disabled, yet this application has SAML directories. This is a configuration error.`
