### ISSUE TITLE
/assets/css/stormpath.css and /assets/js/stormpath.js handler mapping order problems

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#765]
In this example app:

https://github.com/stormpath/stormpath-spring-boot-i18n-test

The i18n messages and the stormpath css/js are not rendered.  The assets are only rendered if you enable the `WebConfig` class (uncomment the `@Configuration` annotation), which explicitly has to fuddle with handler mapping order to get things to work.

App developers should not have to do this handler mapping stuff by default.

**Comment by mraible** [comment]
@lhazlewood This issue appears to be caused by `@EnableConfigServer`. If I remove that annotation, the CSS and JS are rendered just fine. `META-INF/resources` is added automatically by Spring Boot. 

https://spring.io/blog/2013/12/19/serving-static-web-content-with-spring-boot

**Comment by mraible** [comment]
As far as i18n messages, uncommenting the `@Bean` on the following method fixes that. 

```java
@Bean
public MessageSource messageSource() {
    ResourceBundleMessageSource src = new ResourceBundleMessageSource();
    src.setBasename("com.stormpath.sdk.servlet.i18n");
    src.setDefaultEncoding("UTF-8");
    return src;
}
```

Do you want to have this in Stormpath's config by default?

**Comment by mraible** [comment]
I believe this is the mapping performed by Spring Cloud Config Server that causes our asset locations to fail:

```
2016-07-18 11:30:45.137  INFO 6099 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/{name}/{profiles}/{label:.*}],methods=[GET]}" onto public org.springframework.cloud.config.environment.Environment org.springframework.cloud.config.server.environment.EnvironmentController.labelled(java.lang.String,java.lang.String,java.lang.String)
```

**Comment by mraible** [comment]
@lhazlewood After looking into this a bit more today, and reading [this article](https://spring.io/guides/gs/centralized-configuration/), I don't think Spring Config Server was meant to serve up any files other than config files. 

> You can use Spring Cloud’s `@EnableConfigServer` to standup a config server that other applications can talk to. 

AFAICT, Spring Boot applications should talk to this server and have security configured on them, not on the config service itself.

**Comment by lhazlewood** [comment]
@mraible the reason for serving other files is for the same reason we're using the Stormpath plugin with the config server: to secure it (with login pages, etc).

The config server doesn't have any security at all by default because the Spring team is allowing you to set up your own mechanisms (e.g. Spring Security or not).  I'm pretty sure they didn't intend *not* to allow anyone to deploy their own pages.  In fact, you can set the config path to be something different than `/` (e.g. `spring.cloud.config.server.prefix = /config`) and that avoids the path conflicts.

That said, I wonder if this goes away once we have our filter approach working instead of terminal MVC controllers?  This would allow us to intercept and render calls for known paths (like /assets/js/stormpath.js) and allow all others to fall through, avoiding handler mapping order issues entirely.  cc @mrioan

**Comment by lhazlewood** [comment]
now that the filter-instead-of-handler-mapping approach is implemented, I think this problem goes away.  I'm reassigning to myself so I can test/verify.
