### ISSUE TITLE
`stormpath.web.verifyEmail.enabled` validation at startup

### ISSUE THREAD

**Issue by lhazlewood** [stormpath/stormpath-sdk-java#772]
If `stormpath.web.verifyEmail.enabled = true` and the application's default account store does not have an enabled verification workflow this is a conflicting configuration and the user should be notified of this.

1.0 spec here:

https://github.com/stormpath/stormpath-framework-spec/blob/1.0/configuration.md#account-store-resolution

The spec doesn't indicate how the user should be notified - just that they should be notified.   Until that is defined I believe we should 1) gracefully degrade by automatically changing the runtime to reflect the current state of the system and 2) notifying the user of the conflict (e.g. `log.warn`);

**Comment by mraible** [comment]
@lhazlewood How do I get the application's default account store? Once I have that, how do I check to see if it has enabled verification workflow? 

Should this verification happen in `com.stormpath.sdk.servlet.config.ConfigLoader` or somewhere else?

**Comment by lhazlewood** [comment]
@mraible I'm sorry for the confusion, I thought this was assigned to me :/

I'm finishing it as part of my work on #333

**Comment by lhazlewood** [comment]
ah, dangit!  I thought this was for `stormpath.web.register.enabled` checks.  In any event, I think we should do it the same way I did it for #333.

**Comment by lhazlewood** [comment]
In investigating this further, I'm not sure we can/should do this:

- if an account is created in *any* directory that has email verification enabled (regardless if it is an application's default account store or not), then a `/verify` route will need to exist.  If an app is mapped with hundreds or thousands of account stores (e.g. organizations for a multi-tenant app), then you'd have to check if *all* of them have disabled verification in order to actually turn off the route automatically.

I think this is a case where the `stormpath.web.verifyEmail.enabled` property alone is the best bet, or app developers can simply change their login template for custom logic.

**Comment by lhazlewood** [comment]
Moving to the backlog - maybe we can do this in a nice way some day in the future - e.g. if the app has less than 100 account stores (since we can get them all in 1 request), we can check each one and if all of their workflows are disabled, we can gracefully degrade.

Even then that may not work if, for each account store, we have to query for the workflow status, which would imply 1+100 individual requests at most - not nice.
