### ISSUE TITLE
Spring integrations do not return WWW-Authenticate header with 401

### ISSUE THREAD

**Issue by mraible** [stormpath/stormpath-sdk-java#775]
When a server responds with 401, it `MUST` (per the HTTP RFC for [HTTP Authentication](https://tools.ietf.org/html/rfc7235#section-3.1)) set the `WWW-Authenticate` header to explain what means of authentication are supported.

A TCK PR has tests for this, all spring integrations are currently failing:

https://github.com/stormpath/stormpath-framework-tck/pull/293

**Comment by mrioan** [comment]
@mzumbadoate please check that this is solved in branch 542_filter-based_content_rendering

**Comment by mraible** [comment]
@mrioan I can confirm it is solved for `examples/spring-webmvc`.

**Comment by lhazlewood** [comment]
@dogeared isn't this resolved based on the merges you did last night?

**Comment by dogeared** [comment]
Yes. This issue can be closed.

Micah Silverman
