### ISSUE TITLE
Add support for application/x-www-form-urlencoded in verify endpoint

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#781]
According to [spec](https://github.com/stormpath/stormpath-framework-spec/blob/master/email-verification.md) a request like this should be supported:

```
http POST http://localhost:8080/verify sptoken==XXX Accept:application/x-www-form-urlencoded
```

However it seems that our Content Negotiation component is not able to support this.

We get this error: `No MediaType could be resolved for this request (application/x-www-form-urlencoded) and the configured producesMediaTypes settings (application/json,text/html). The ContentNegotiationResolver was not able to come up with a valid MediaType.`

**Comment by mraible** [comment]
@mrioan `http POST http://localhost:8080/verify sptoken==XXX Accept:application/x-www-form-urlencoded` responds with a 200 OK with Spring MVC. Is this the example app that I should be testing against?

**Comment by mraible** [comment]
I was able to reproduce this issue with servlet.
