### ISSUE TITLE
allow enable = false in servlet implementation

### ISSUE THREAD

**Issue by wgorman** [stormpath/stormpath-sdk-java#790]
DefaultFilterChainResolverFactory has no way of disabling filters such as "register", etc.  I recommend adding the property "stormpath.web.register.enabled" and supporting that flag in the Factory.

**Comment by mraible** [comment]
In 1.0, you'll have the ability to disable registration using `stormpath.web.register.enabled = false`. Does that satisfy your issue?

**Comment by wgorman** [comment]
Yes, that would.  I saw that capability in the SpringBoot implementation.  When will 1.0 be available?  Thanks,  Will

**Comment by mraible** [comment]
@wgorman We're hoping to release 1.0 by early next week.
