### ISSUE TITLE
Disable Stormpath in Web App

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#802]
We need a way to disable Stormpath for good in a Web Application that depends on us. 

`stormpath.web.enabled = false` doesn't totally disable Stormpath as it is still asking for the `ApiKey`.

For reference see ticket 8668

**Comment by lhazlewood** [comment]
`stormpath.web.enabled` should only disable the web stuff.

`stormpath.enabled = false` should disable everything.
