### ISSUE TITLE
`next` param replication

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#823]
In the `Spring Security WebMVC Example`, when you hit an endpoint that requires auth, it redirects to `/login`. This is correct. However, the `next` param keeps getting appended to each subsequent `Location` header value.

Steps to reproduce:

1. curl -v -H "Accept: text/html" http://localhost:8080/missing
    * **returns**: 302, `Location: /login?next=%2Fmissing`
1. curl -v -H "Accept: text/html" http://localhost:8080/missing
    * **returns**: 302, `Location: /login?next=%2Fmissing?next=%2Fmissing`
1. curl -v -H "Accept: text/html" http://localhost:8080/missing
    * **returns**: 302, `Location: /login?next=%2Fmissing?next=%2Fmissing?next=%2Fmissing`

**Comment by mraible** [comment]
This happens in Spring MVC as well, as evidenced by this failing TCK test.

```
  Run 29: LoginIT.testNoRedirectionStickinessHtml:797 1 expectation failed.
Expected header "Location" was not doesn't match path, was "http://localhost:8080/login?next=%2Fme%3Ffoo%3Dbar?next=%2Fme". Headers are:
Server=Apache-Coyote/1.1
Cache-Control=no-store, no-cache
Pragma=no-cache
Location=http://localhost:8080/login?next=%2Fme%3Ffoo%3Dbar?next=%2Fme
Content-Type=application/json
Content-Length=0
Date=Mon, 01 Aug 2016 16:31:30 GMT
```
