### ISSUE TITLE
`ash` claim not set for token on SAML initiation with Spring Boot WebMVC

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#825]
Steps to reproduce:

1) Start the Spring WebMVC example connected to an application that has a SAML directory mapped to it.
2) Observe that you are able to log in properly. If you capture the JWT sent to the backend, it will be something like this:

    eyJ0eXAiOiJKV1QiLCJraWQiOiJSOTJTQkhKQzFVNERBSU1HUTNNSE9HVk1YIiwiYWxnIjoiSFMyNTYifQ.eyJjYl91cmkiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvc3Rvcm1wYXRoQ2FsbGJhY2siLCJhc2giOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2RpcmVjdG9yaWVzLzZMOFVUR0paTzdiYlBZa2ZCcmZaVGoiLCJqdGkiOiJlMTQwMTc2Mi1mNThkLTRlMzYtYmQ5Ny0xMzBhNzljNDE4Y2EiLCJpYXQiOjE0Njk5OTE0MjEsImlzcyI6IlI5MlNCSEpDMVU0REFJTUdRM01IT0dWTVgiLCJzdWIiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy82dkZUNEFSZldDbXVIVlY4Vmt0alRvIn0.qqkYeOzzehNXPrWS8vUdfnW-Sp6uLBgNqEFLTOjLZII

    Notice that when decoded, the `ash` claim is set.

3) Start the Spring Boot WebMVC example connected to the same application as step 1
4) Observe that you get a 401 error from the backend when you try to log in. You will see a JWT like this:

    eyJ0eXAiOiJKV1QiLCJraWQiOiJSOTJTQkhKQzFVNERBSU1HUTNNSE9HVk1YIiwiYWxnIjoiSFMyNTYifQ.eyJjYl91cmkiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvc3Rvcm1wYXRoQ2FsbGJhY2siLCJhc2giOiIiLCJqdGkiOiIxODY1YzdiZC1iODRiLTRmODctOTYxZi0zMTg3MTMyNTkxNzEiLCJpYXQiOjE0Njk5OTEwNzksImlzcyI6IlI5MlNCSEpDMVU0REFJTUdRM01IT0dWTVgiLCJzdWIiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy82dkZUNEFSZldDbXVIVlY4Vmt0alRvIn0.j_pjz5iFRtRZHwXORoR4UAg277wPUyj8iFOIOMU7E0g

    Notice that when decoded, there is no `ash` claim.

**Comment by mrioan** [comment]
@dogeared I could not reproduce this issue. You might have read the `access_token` rather than the `jwtResponse`. I am pasting here the obtained requests and responses for Spring and Spring Boot:

## Request Spring
```
https://api.stormpath.com/v1/applications/1S8dngn3dKJ7bdwDNldDav/saml/sso/idpRedirect?accessToken=eyJ0eXAiOiJKV1QiLCJraWQiOiIyRkpDNTlYNjUzQkxVMUgzUUtJN09FNEU3IiwiYWxnIjoiSFMyNTYifQ.eyJjYl91cmkiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvc3Rvcm1wYXRoQ2FsbGJhY2siLCJhc2giOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2RpcmVjdG9yaWVzLzNPeHRNTlg5NzR6VERPNDVGemFhSjMiLCJqdGkiOiI0NWVmMGQ2ZS1iYWMzLTQyN2UtOWNmNi03ZTAxOGM1Y2E0ODMiLCJpYXQiOjE0NzAwNjA4NjUsImlzcyI6IjJGSkM1OVg2NTNCTFUxSDNRS0k3T0U0RTciLCJzdWIiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy8xUzhkbmduM2RLSjdiZHdETmxkRGF2In0.NcQFFVoBF8Spj6CFkJO2IITDsaBW0p62wZw23NZ1hPI
```
## Response Spring
```
eyJzdHQiOiJhc3NlcnRpb24iLCJraWQiOiIyRkpDNTlYNjUzQkxVMUgzUUtJN09FNEU3IiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy8xUzhkbmduM2RLSjdiZHdETmxkRGF2Iiwic3ViIjoiaHR0cHM6Ly9hcGkuc3Rvcm1wYXRoLmNvbS92MS9hY2NvdW50cy8xeDdCbXpHaDNyYWVpUkhpbERvdjNhIiwiYXVkIjoiMkZKQzU5WDY1M0JMVTFIM1FLSTdPRTRFNyIsImV4cCI6MTQ3MDA2MDk1NSwiaWF0IjoxNDcwMDYwODk1LCJqdGkiOiIyOWZlYWQwMy0wYjI4LTQ5MmEtODg4OS1iMjQ2MTVkODBiYmUiLCJpcnQiOiJmZmE4NzE3ZC02M2E0LTRmYTMtOTI0Ny03NzUyZmYyNTUzYTMiLCJpc05ld1N1YiI6ZmFsc2UsInN0YXR1cyI6IkFVVEhFTlRJQ0FURUQifQ.N1Vl_fwEWyhlmrrFCuF4d7rFuBTGWQYZBiWpEWMylCs
```

## Request Boot
```
https://api.stormpath.com/v1/applications/1S8dngn3dKJ7bdwDNldDav/saml/sso/idpRedirect?accessToken=eyJ0eXAiOiJKV1QiLCJraWQiOiIyRkpDNTlYNjUzQkxVMUgzUUtJN09FNEU3IiwiYWxnIjoiSFMyNTYifQ.eyJjYl91cmkiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvc3Rvcm1wYXRoQ2FsbGJhY2siLCJhc2giOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2RpcmVjdG9yaWVzLzNPeHRNTlg5NzR6VERPNDVGemFhSjMiLCJqdGkiOiI4OTM0OGNjZC1hN2UxLTRiYWYtYWQ0YS1lMTVkMDlkYzQxY2MiLCJpYXQiOjE0NzAwNjA0NDYsImlzcyI6IjJGSkM1OVg2NTNCTFUxSDNRS0k3T0U0RTciLCJzdWIiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy8xUzhkbmduM2RLSjdiZHdETmxkRGF2In0.3fTawK5I-87ttEmphPRtmO24Qc2S-MnuVgccGb7MDCw
```

## Response Boot

```
eyJzdHQiOiJhc3NlcnRpb24iLCJraWQiOiIyRkpDNTlYNjUzQkxVMUgzUUtJN09FNEU3IiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy8xUzhkbmduM2RLSjdiZHdETmxkRGF2Iiwic3ViIjoiaHR0cHM6Ly9hcGkuc3Rvcm1wYXRoLmNvbS92MS9hY2NvdW50cy8xeDdCbXpHaDNyYWVpUkhpbERvdjNhIiwiYXVkIjoiMkZKQzU5WDY1M0JMVTFIM1FLSTdPRTRFNyIsImV4cCI6MTQ3MDA2MDUyNiwiaWF0IjoxNDcwMDYwNDY2LCJqdGkiOiJmNTVlNjY1ZC0wNzkyLTQ3ZWQtYmFjNi0yNWQyN2E2ZTFkNTUiLCJpcnQiOiI4OTM0OGNjZC1hN2UxLTRiYWYtYWQ0YS1lMTVkMDlkYzQxY2MiLCJpc05ld1N1YiI6ZmFsc2UsInN0YXR1cyI6IkFVVEhFTlRJQ0FURUQifQ.grjr-eNd64c5-cbyxraD6ZwLVmwg6laZ5Io0ot71fbU
```
