### ISSUE TITLE
Spring Boot: revoked token can still be used as Bearer token

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#861]
This has been verified in Spring Boot only, but the other integrations should be checked when the issue is solved.

May be a caching issue.

Steps to reproduce:

1. Start the Spring Boot WebMVC example in the SDK
2. Ensure that there are no access tokens for a user on the backend

    ![image](https://cloud.githubusercontent.com/assets/364562/17418033/3a5c3588-5a4b-11e6-8b27-665a55c805ea.png)

3. Obtain an access token: `http -f POST localhost:8080/oauth/token grant_type=password username=<email> password=<password>`
4. Verify that the token is allocated on the backend

    ![image](https://cloud.githubusercontent.com/assets/364562/17418084/729fab64-5a4b-11e6-87c5-ba5c58f2f65a.png)

5. logout: `http POST localhost:8080/logout Cookie:"access_token=<access token>"`
6. Confirm that the access token has been removed on the backend

    ![image](https://cloud.githubusercontent.com/assets/364562/17418120/abb4b96c-5a4b-11e6-86da-42a2e59e0f34.png)

7. Use the (now revoked) access token as a bearer token: `http localhost:8080 Authorization:"Bearer <revoked access token>"

You will see in the response, that the app is still able to use the token to lookup your users information.

```
...
<h1>Hello, Micah!</h1>
...
```

**Comment by edjiang** [comment]
The default config is local validation, which means it will not respect revocation lists. Are you sure this is a bug?

**Comment by dogeared** [comment]
If you explicitly log out (as shown in the steps to reproduce), you should no longer be able to use the token.

This is differs then if the token is just revoked on the backend - this is actually hitting the /logout endpoint of the spring boot app.

Micah Silverman

**Comment by edjiang** [comment]
Yep, if you're using local validation this is expected behavior from app.

**Comment by edjiang** [comment]
https://github.com/stormpath/stormpath-framework-spec/blob/master/oauth2.md#stormpathweboauth2passwordvalidationstrategies

**Comment by dogeared** [comment]
Closing per @edjiang
