### ISSUE TITLE
Spring Boot: stormpath.web.register.nextUri setting is not honored

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#862]
This has been tested with Spring Boot, but should be confirmed in the other integrations as well.

The default setting is: `stormpath.web.register.nextUri = /`

However, after registering, you are redirected back to the login page with a status: `http://localhost:8080/login?status=created`

![image](https://cloud.githubusercontent.com/assets/364562/17418214/31880242-5a4c-11e6-9917-69567d100381.png)

![image](https://cloud.githubusercontent.com/assets/364562/17418247/68f033a8-5a4c-11e6-9ba0-89ce05688a0a.png)

If the default should be `/login?status=created`, that's fine, but if it is set, it should go to whatever the setting is after successful registration.

**Comment by jarias** [comment]
Talking to @dogeared looks like this is working per spec

```
The newly created account's status is ENABLED and autoLogin is:

    - True: issue a 302 Redirect to the nextUri and log the user in (create the OAuth2 token cookies).
    - False: 302 redirect the user to stormpath.web.login.uri, and append the query parameter ?status=created (see login page status messages).

The newly created account status is UNVERIFIED, then 302 redirect the user to stormpath.web.login.uri and append the query parameter ?status=unverified (see login page status messages).
```
