### ISSUE TITLE
Disable Servlet Plugin

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#871]
Our Servlet plugin cannot currently being totally disabled. Endpoints can but not the Servlet. 

For example, an application that has the servlet plugin integrated will never be able to boot if the `apiKey.properties` file is not present. 

We would need to provide a way (programmatically?) to avoid the Servlet plugin to even start.

We want to support this in Spring and Spring Boot as well (Spring Boot should already be working, so this needs to be actually validated)

For reference see ticket 8668

**Comment by dogeared** [comment]
`stormpath.enabled = false` should turn off Stormpath altogether
`stormpath.web.enabled = false` should turn off servlet filter
