### ISSUE TITLE
Change the uses of 'nextUri' for getNextUri() in the endpoint Controllers

### ISSUE THREAD

**Issue by mzumbadoate** [stormpath/stormpath-sdk-java#874]
The 'nextUri' property can be override by a query paramater. 
In AbstractController there is a getNextUri method that checks for the query param.
If the controllers use 'nextUri' instead of getNextUri the query param will not take effect

**Comment by jarias** [comment]
@mzumbadoate I think the next query param is only for login.

 @dogeared @mrioan what do you guys think?
