### ISSUE TITLE
Disabling login endpoint also disables login functionality

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#894]
Setting `stormpath.web.login.enabled = false` does not only disable the `/login` endpoint. It also removes functionality that causes internal code not to be able to proceed with an authenticated request.

For example, a request where `client_credentials` are provided will be properly authenticated by the AccountResolver but subsequent internal functionality will consider the request to be unauthenticated.

I think the issue is related to Account Saver functionality not being available when the login has been disabled.

**Comment by josebarrueta** [comment]
I tried to secure my application using stormpath.springboot-starter dependency and wanted to only use the ApiKey authentication to secure my endpoints.

`        <dependency>
            <groupId>com.stormpath.spring</groupId>
            <artifactId>stormpath-default-spring-boot-starter</artifactId>
            <version>1.0.2</version>
        </dependency>
`

`
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.apply(stormpath())
                .and()
                .authorizeRequests()
                .antMatchers("/health").anonymous()
                .antMatchers("/metrics").anonymous()
                .antMatchers("/**").fullyAuthenticated();
    }
`

The configuration I set in the application.properties:

`
stormpath.web.login.enabled = true
stormpath.web.logout.enabled = false
stormpath.web.forgotPassword.enabled = false
stormpath.web.changePassword.enabled = false
stormpath.web.register.enabled = false
stormpath.web.verifyEmail.enabled = false
stormpath.web.oauth2.enabled = false
stormpath.web.idSite.enabled = false
stormpath.web.callback.enabled = false
stormpath.web.me.enabled = false
`

However the service wasn't able to authenticate the call at all (using valid api key id/secret):

`
http -a apiKeyId:apiKeySecret http://localhost:8080/nameRecords application:='{"href":"https://api.stormpath.com/v1/dfdsfdsj"}'
HTTP/1.1 403
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json;charset=UTF-8
Date: Thu, 11 Aug 2016 19:35:39 GMT
Expires: 0
Pragma: no-cache
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block

{
    "error": "Forbidden",
    "message": "Access Denied",
    "path": "/nameRecords",
    "status": 403,
    "timestamp": 1470944139932
}
`

Thanks to @mrioan for suggesting to enable the login propery (i.e. `stormpath.web.login.enabled = true`), after

**Comment by josebarrueta** [comment]
UPDATE: I could solve this issue (disabling the login property by adding ```springSecurityResolvedAccountFilter``` to the ```HttpSecurity``` bean (as enabling login does).

```
    @Autowired
    private SpringSecurityResolvedAccountFilter springSecurityResolvedAccountFilter;

    .... 
 
    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http.apply(StormpathWebSecurityConfigurer.stormpath())
                .and()
                .addFilterBefore(springSecurityResolvedAccountFilter, AnonymousAuthenticationFilter.class)
                .authorizeRequests()
                .antMatchers("/health").anonymous()
                .antMatchers("/metrics").anonymous()
                .antMatchers("/**").fullyAuthenticated();
    }
```
