### ISSUE TITLE
Add filter search to searchable collections

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#900]
In the C# library, you can do a filter search like:

```
var accountsContainingLuc = await myApplication
    .GetAccounts()
    .Filter("Luc")
    .ToListAsync();
```

The closest we currently have in the JSDK is:

```
Map<String, Object> queryParams = new HashMap<>();
queryParams.put("q", "Luc");
AccountList accounts = application.getAccounts(queryParams);
```

We should add a method to our collection search objects (Like `Accounts`) so that we could do a filter search like:

```
AccountList accounts = application.getAccounts(
   Accounts.filter("Luc")
);
```

Behind the scenes, it would do the `q=Luc` request.

**Comment by lhazlewood** [comment]
I added this back to ready since there are a lot more changes expected and @mzumbadoate is out on vacation.
