### ISSUE TITLE
StormpathFilter must be behind Spring Security Filter

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#915]
Relates to #892 #1145

**Comment by mrioan** [comment]
@dogeared I moved this issue back to `in progress` so the TCK tests can be fixed. I also assigned it to you. Thanks for handling this!

**Comment by bdemers** [comment]
I had to do something similar in stormpath/stormpath-shiro. The current solution isn't ideal, it basically just grabs the Stormpath `FilterRegistrationBean`, disables it, and then sticks the Stormpath filter in Shiro's filterChainResolver.  

I'd like to have a better solution around this, it doesn't necessarily need to be part of this issue, but, i'm adding this note for consideration.

**Comment by mrioan** [comment]
@bdemers sure!, we should definitively try to see if there is a solution that can be shared among both frameworks, that would be great!

When we finally decide to work on this we need to share what is the current status for each framework and brainstorm about possible solutions.

**Comment by mrioan** [comment]
A first approach to this issue was implemented in https://github.com/stormpath/stormpath-sdk-java/pull/919 but it was closed now as it is very out of date now
