### ISSUE TITLE
Create a single top-level docs folder for all integrations

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#949]
Following the structure of [stormpath-documentation](https://github.com/stormpath/stormpath-documentation), we should have a single docs folder that we can generate integration-specific documentation sets from.

Currently, we have a `docs` folder in the root of the project for servlet and we have spring boot specific docs in `extensions/spring/boot/docs`.

We'll want to integrate the spring boot specific docs into the top level docs and have directives to switch between integrations (currently spring boot and servlet).

This will reduce duplication and make it easier to add docs for other integrations.

We'll need to update the `Makefile` and the `.travis.yml` file as well.

Example of `only` directive, used to switch between languages (integrations, in our case) is [here](https://raw.githubusercontent.com/stormpath/stormpath-documentation/develop/source/quickstart.rst)

Example `Makefile` to build different languages is [here](https://github.com/stormpath/stormpath-documentation/blob/develop/Makefile)

**Comment by mraible** [comment]
@dogeared What command do I use to generate the different languages?

**Comment by mraible** [comment]
Nevermind, the [readme.md](https://github.com/stormpath/stormpath-documentation/blob/develop/readme.md) documents this well:

#### Generating Static Docs

`make html` will generate the REST Product Guide as HTML.

`make html LANGUAGE={name}` will generate the Product Guide for the specified language.

The possible values for `{name}` are:

- `rest`
- `php`
- `java`
- `csharp`
- `vbnet`
- `python`
- `nodejs`

If you would like to generate all of the Product Guides in one go, you can use the same command that Travis uses:

`make allhtml`

This will iterate through every language and generate the Product Guide for that language.

**Comment by adamstormpath** [comment]
Need to talk to Randall about doc navigation.
