### ISSUE TITLE
Quickstart link in Java SDK section of docs page should point to product guide

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-sdk-java#956]
Location should be: https://docs.stormpath.com/java/product-guide/latest/quickstart.html

**Comment by dogeared** [comment]
![image](https://cloud.githubusercontent.com/assets/364562/18285288/b7408950-743b-11e6-97fd-8da67bafe5aa.png)

**Comment by lhazlewood** [comment]
@jakubswiatczak fixed this before we had a chance to merge the linked PR, so we can close this now.
