### ISSUE TITLE
Support stormpath_token grant type

### ISSUE THREAD

**Issue by jarias** [stormpath/stormpath-sdk-java#957]
We need to make sure that we support stormpath_token grant type

https://stormpath.atlassian.net/wiki/display/AM/ID+Site+OAuth+Access+Token+Grant+Type

And add the proper authenticator according to the spec, we currently have an ID_SITE_AUTHENTICATOR that should actually be StormpathAssertionAuthenticator and we also need to adds OAuthStormpathTokenAuthenticator

https://github.com/stormpath/stormpath-sdk-spec/blob/master/specifications/authenticators.md

**Comment by jarias** [comment]
@mraible while looking that the code the ID_SITE_AUTHENTICATOR is actually the OAuthStormpathTokenAuthenticator and we are missing the StormpathAssertionAuthenticator

**Comment by mraible** [comment]
@jarias Are you suggestion I rename ID_SITE_AUTHENTICATOR to OAUTH_STORMPATH_TOKEN_AUTHENTICATOR (and DefaultIdSiteAuthenticator* to DefaultOauthStormpathTokenAuthenticator)? As far as `StormpathAssertionAuthenticator`, does that need to be created?

**Comment by mrioan** [comment]
We still do not understand this feature good enough. Opens:

1. How is the IDSIte token generated?
2. Should `Authenticators.ID_SITE_AUTHENTICATOR` be removed (deprecated until it can be removed in next major release)?

**Comment by mraible** [comment]
Fixed by #1127.
