### ISSUE TITLE
Resource "deepCopy" function is suitable to be open for reuse

### ISSUE THREAD

**Issue by mrioan** [stormpath/stormpath-sdk-java#962]
See: https://github.com/stormpath/stormpath-sdk-java/pull/953#discussion_r77816257

**Comment by mzumbadoate** [comment]
@mrioan in those comments (#953) you ask to refactor 
ResourceToMapConverter deepCopy function and toMap function to ResourceUtils

1. we don't have a ResourceUtils class, we have 'com.stormpath.sdk.impl.resource.ResourceUtil'

2. ResourceToMapConverter was renamed to ResourceMapFunction

do you want a new ResourceUtils class in the SDK side?
is this ticket still relevant?
do we want this for 1.1.1?
